### DISCUSSION TITLE
How can I generate model with exported model validation methods?

### DISCUSSION THREAD

**Discussion by abdullahskartal** [go-swagger/go-swagger#2715] [Q&A] [answered]
I have swagger.yaml like

```
CreateUser:
  type: object
  properties:
    firstName:
      type: string
      maxLength: 32
```

When I generate model with `generate model` there is a Validate() method for use validation but I need to validate parameters one by one into the handler. For instance my generated model like;

```
func (m *CreateUser) validateFirstName(formats strfmt.Registry) error {

	if err := validate.Required("firstName", "body", m.FirstName); err != nil {
		return err
	}

	if err := validate.MaxLength("firstName", "body", *m.FirstName, 32); err != nil {
		return err
	}

	return nil
}
```

I need to access validateFirstName method from outside to model file but validateFirstName method is unexported.
How can I generate model with exported model validation methods?
