### DISCUSSION TITLE
How to set strfmt.Date format

### DISCUSSION THREAD

**Discussion by KabudoWiseMan** [go-swagger/go-swagger#2848] [Q&A]
Hello!

In a yml file a have the following definition:
```yaml
individualDocument:
...
  startPeriod:
          type: string
          format: date
...
```

So I generate go-client and get:
```go
type IndividualDocument struct {
	StartPeriod strfmt.Date `json:"startPeriod,omitempty"`
}
```

The thing is that the returning value is **2020-07-18T00:00:00Z**, so I get an error **parsing time "2020-07-18T00:00:00Z": extra text: "T00:00:00Z"**.

So my question is how can I change parsing time format?

Thanks!
