### ISSUE TITLE
Bad code generated for querystring items pattern validation

### ISSUE THREAD

**Issue by jeffandersen** [go-swagger/go-swagger#1010]
## Problem statement

A query parameter, specified as an array, breaks when using pattern for items.

## Swagger specification

```
/widgets/:
  get:
    summary: Retrieve all widgets.
    parameters:
      - name: category_id
        in: query
        description: Return the widgets that are associated with this category.
        required: true
        type: array
        collectionFormat: "multi"
        items:
          type: string
          pattern: '^[0-9abcdefghjkmnpqrtuvwxyz]{29}$'
          format: base32ID
```

The code generated for this route's parameters ends up with an incorrect variable name:

```
func (o *GetWidgetsParams) bindCategoryID(rawData []string, hasKey bool, formats strfmt.Registry) error {
  if !hasKey {
    return errors.Required("category_id", "query")
  }

  categoryIDIC := rawData

  if len(categoryIDIC) == 0 {
    return errors.Required("category_id", "query")
  }

  var categoryIDIR []string
  for i, categoryIDIV := range categoryIDIC {
    categoryIDI := categoryIDIV

    if err := validate.Pattern(fmt.Sprintf("%s.%v", "category_id", i), "query", category_idI, `^[0-9abcdefghjkmnpqrtuvwxyz]{29}$`); err != nil {
      return err
    }

    categoryIDIR = append(categoryIDIR, categoryIDI)
  }

  o.CategoryID = categoryIDIR

  return nil
}
```

Note the `validate.Pattern` line.

It attempts to consume `category_idI` not `categoryIDI` as defined the line above.
