### ISSUE TITLE
How to validate the body?

### ISSUE THREAD

**Issue by bobvanluijt** [go-swagger/go-swagger#1025]
This example shows one of the handlers. It now simply returns the "createdCode" that is set for this event.

```
api.LocationsWeaviateLocationsInsertHandler = locations.WeaviateLocationsInsertHandlerFunc(func(params locations.WeaviateLocationsInsertParams) middleware.Responder {

    // do stuff based on params.Body

    return middleware.ResponderFunc(func(rw http.ResponseWriter, p runtime.Producer) {
        rw.WriteHeader(locations.WeaviateLocationsInsertCreatedCode)
    })
})
```

I would like to know how I can validate `params.Body`. I don't seem to be able to find the correct validation function.

**Comment by casualjim** [comment]
it's already validated by the time you get it

**Comment by bobvanluijt** [comment]
Hi @casualjim, thx but I actually mean the expected body.

If I POST a body which is not the body from the definition it is still accepted.

### Example

If I have this definition

```
definitions:
    Example:
        description: Example definition.
        properties:
            foo:
                default: 'case'
                description: This is a test string
                type: string
            bar:
                default: 'case'
                description: This is another test string
                type: string
```

and I POST:

```
{
  "test":"case"
}
```

It still is 'valid'. That is why I would like to validate `params.Body` against what is in the Swagger document.
