### ISSUE TITLE
How to accept an API-KEY?

### ISSUE THREAD

**Issue by bobvanluijt** [go-swagger/go-swagger#1039]
Hi all,

What should I do to accept the `X-API-KEY`? It now always returns not authenticated. Even if `X-API-KEY` = `foobar`.

```
// Applies when the "X-API-KEY" header is set
api.KeyAuth = func(token string) (interface{}, error) {

    if token == "foobar" {
        println("ACCEPT")
        return nil, nil
    }

    return nil, errors.New(401, "incorrect api key auth")
}
```

Swagger security part:
```
securityDefinitions:
  apiKey:
    type: apiKey
    in: header
    name: X-API-KEY
security:
  - key: []
```
