### ISSUE TITLE
Could I change a response of when validation error ?

### ISSUE THREAD

**Issue by hiyosi** [go-swagger/go-swagger#1041]
How could I change responses of validation error.

The default response when the required field is empty is the following.

```
HTTP/1.1 422 Unprocessable Entity

{
  "code": 602,
  "message": "xxx in body is required"
}
```

But, I want to change responses like as follows.

```
HTTP/1.1 422 Unprocessable Entity

{
  "code": 422,
  "version": "v1",
  "status": "Failure",
  "message": "xxx in body is required"
}
```

The definition of swagger looks something like this.
```
  ValidationError:
    type: "object"
    properties:
      version:
        type: "string"
      status:
        type: "string"
        enum: ["Success", "Failure"]
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
```
