### ISSUE TITLE
invalid enum constants

### ISSUE THREAD

**Issue by ripienaar** [go-swagger/go-swagger#1047]
## Problem statement

Enums alias constants are generated with the same name leading to compile errors

```go
// models/fact_filter.go
const (
        // FactFilterOperator captures enum value "=="
        FactFilterOperator string = "=="
        // FactFilterOperator captures enum value "=~"
        FactFilterOperator string = "=~"
        // FactFilterOperatorNrBang captures enum value "!="
        FactFilterOperatorNrBang string = "!="
        // FactFilterOperator captures enum value ">="
        FactFilterOperator string = ">="
        // FactFilterOperator captures enum value ">"
        FactFilterOperator string = ">"
        // FactFilterOperator captures enum value "<="
        FactFilterOperator string = "<="
        // FactFilterOperator captures enum value "<"
        FactFilterOperator string = "<"
)
```
## Swagger specification

```yaml
definitions:
  word:
    type: string
    minLength: 1
    pattern: '^[a-zA-Z0-9_\-\.]+$'
  wordOrRegex:
    type: string
    minLength: 1
    pattern: '^((\\/[a-zA-Z0-9\\.\\-_]+\/)|([a-zA-Z][a-zA-Z0-9\\.\\-_]+))$'
  factFilter:
    type: object
    required:
      - fact
      - operator
      - value
    properties:
      fact:
        $ref: '#/definitions/word'
      operator:
        type: string
        enum:
          - "=="
          - "=~"
          - "!="
          - ">="
          - ">"
          - "<="
          - "<"
      value:
        $ref: '#/definitions/wordOrRegex'
  factsFilter:
    type: array
    items:
      $ref: '#/definitions/factFilter'
```

## Environment
swagger version: dev from 2 days ago
go version: 1.8.1
OS:   macOS 10.12.4

**Comment by fredbi** [comment]
My suggestion to solve this puzzle is to avoid constant generation when it makes no sense to infer a name from a value and let the user define custom names for its values if she wants to reuse them in its app.

Here is an example based on this testcase:
```yaml
      operator:
        type: string
        enum:
          - "=="
          - "=~"
          - "!="
          - ">="
          - ">"
          - "<="
          - "<"
```
=> no constant generated
```yaml
      operator:
        type: string
        enum:
          - "=="
          - "=~"
          - "!="
          - ">"
          - "<="
          - "<"
        x-go-const-names: 
          - Equal
          - Match
          - NotEqual
          - Greater
          - LessOrEqual
          - Less
```
Would generate this:
```golang
const (
	// Equal captures enum value ==
	Equal = "=="

	// Greater captures enum value >=
	Greater = ">="

	// Less captures enum value <=
	Less = "<="

	// LessOrEqual captures enum value >
	LessOrEqual = ">"

	// Match captures enum value =~
	Match = "=~"

	// NotEqual captures enum value !=
	NotEqual = "!="
)
```
