### ISSUE TITLE
type=uint64, minimum=0+exclusiveMinimum vs minimum=1

### ISSUE THREAD

**Issue by maxatome** [go-swagger/go-swagger#1068]
What is the logic behind the code generated using this definition:

```yaml
definitions:
  Info:
    type: object
    properties:
      test_a:
        type: integer
        format: uint64
        minimum: 0
        exclusiveMinimum: true
      test_b:
        type: integer
        format: uint64
        minimum: 1
```
↓
```go
// swagger:model Info
type Info struct {

  // test_a
  // Minimum: > 0
  TestA *uint64 `json:"test_a,omitempty"`

  // test_b
  // Minimum: 1
  TestB uint64 `json:"test_b,omitempty"`
}
```
`TestA` is a pointer on `uint64` but not `TestB`...

swagger version: dev → 220a68f31437616b53c032a5f82384450f82cf4e
go version: 1.7.1
OS: linux/amd64
