### ISSUE TITLE
Missing security import in server api generated code

### ISSUE THREAD

**Issue by YGuyomar** [go-swagger/go-swagger#1085]
Depending on the spec file, code generated for the server might not compile due to a missing import.
What I noticed is this happens particularly when the spec file does not contain securityDefinitions. 

## Swagger specification
Use the default one from http://editor2.swagger.io
See attachment.

## Steps to reproduce
- Generate server:
swagger generate server -f .\swagger.json -A tst

- Vendor packages with any package manager. e.g.:
glide init
glide install

- Build:
go install .\cmd\tst-server

restapi\operations\tst_api.go:34: undefined: security in security.BasicAuth
restapi\operations\tst_api.go:35: undefined: security in security.APIKeyAuth
restapi\operations\tst_api.go:36: undefined: security in security.BearerAuth
restapi\operations\tst_api.go:69: undefined: security in security.UserPassAuthentication
restapi\operations\tst_api.go:72: undefined: security in security.TokenAuthentication
restapi\operations\tst_api.go:75: undefined: security in security.ScopedTokenAuthentication

Manually patching restapi\operations\tst_api.go by adding "github.com/go-openapi/runtime/security" to the imports fixes it. 

## Environment
swagger version: dev - 2ea68fd74988bb7c1a2548f77361dd8ecd5dd880
go version: 1.8.3 
OS:   Windows 10
[swagger.json.txt](https://github.com/go-swagger/go-swagger/files/1112654/swagger.json.txt)

**Comment by arielt** [comment]
From what I saw it depends if you have openapi runtime in GOPATH during the code generation.
Put github.com/go-openapi/runtime in GOPATH, run codegen again and it should work.

**Comment by YGuyomar** [comment]
Arielt,

Thanks for your comment. You are right. That solves the issue, although I usually avoid installing packages globally. 
Other option: generating code again after having vendored dependences (including go-openapi/runtime) works too. 

I did not expect such dependency for code-gen (only for build), maybe it could be documented somewhere, or the template could be updated.
What is strange is that other go-openapi packages are properly imported, except this particular one.

**Comment by casualjim** [comment]
you can also vendor the github.com/go-openapi/runtime

For glide you have to vendor a few more packages explicitly through adding them to glide.yaml because otherwise it doesn't pick them up

here's what I have in my glide.yaml file and I build using a clean golang container every time.

```yaml
- package: github.com/casualjim/middlewares
- package: github.com/go-openapi/errors
- package: github.com/go-openapi/loads
- package: github.com/go-openapi/runtime
  subpackages:
  - client
  - flagext
  - middleware
- package: github.com/go-openapi/spec
- package: github.com/go-openapi/strfmt
- package: github.com/go-openapi/swag
- package: github.com/go-openapi/validate
- package: github.com/justinas/alice
  version: ^1.0.0
```
