### ISSUE TITLE
Security only supports "OR" logic, not "AND"

### ISSUE THREAD

**Issue by gavbaa** [go-swagger/go-swagger#1089]
## Problem statement
When specifying a security block in the AND format (described here: https://swagger.io/docs/specification/authentication/ ), having only one pass allows requests to continue without a 401.

The documentation states:
```
security:
  - A
  - B

 # A OR B
security:
  - A
    B

 # A AND B
```

## Swagger specification
I've included the relevant bit here.  I've put a full test case at https://github.com/gavbaa/go-swagger-auth-test if you want to clone and review directly.  It's the TodoList Swagger file, with only the following security bit added.
```
securityDefinitions:
  AppTokenAuth:
    type: apiKey
    in: header
    name: App-Token
  TokenAuth:
    type: apiKey
    in: header
    name: Token

security:
  - AppTokenAuth: []
    TokenAuth: []
```
## Steps to reproduce
I implemented only the AppTokenAuthAuth function and left TokenAuthAuth returning an error:
```
	api.AppTokenAuthAuth = func(token string) (interface{}, error) {
		return true, nil
		//return nil, errors.NotImplemented("api key auth (AppTokenAuth) App-Token from header param [App-Token] has not yet been implemented")
	}

	// Applies when the "Token" header is set
	api.TokenAuthAuth = func(token string) (interface{}, error) {
		return nil, errors.NotImplemented("api key auth (TokenAuth) Token from header param [Token] has not yet been implemented")
	}
```

However, upon cURLing with just an App-Token, it moves onto the method handler instead of rejecting the request with a 401.

```
➜  ~ curl -H "App-Token: x" "http://127.0.0.1:58282"
"operation todos.Get has not yet been implemented"
```

## Environment
swagger version: 2.0.0 
go version: 1.8.1
OS:  OSX 10.12.5
