### ISSUE TITLE
Nested objects in array are not validated

### ISSUE THREAD

**Issue by ianzapolsky** [go-swagger/go-swagger#1093]
## Problem statement

I have found that in code generated for a swagger object that contains a field which itself is an array of other nested objects, the `Validate` function for the array field is never called. 

The symptom of this problem is that I can submit a parent object with an array of children that are missing their required fields.

Example:
## swagger specification
```
---
ad_profile:
    type: object
    required:
      - id
      - member_id
    properties:
      id:
        type: integer
      member_id:
        type: integer
      members:
        type: array
        items:
          type: object
          required:
            - member_id
            - status
          properties:
            member_id:
              type: integer
            status:
              type: string
```
## generated function to validate AdProfile.Members

This function looks right to me, because it attempts to call `Validate` on each of the items in the array.
```
// Validate validates this ad profile members
func (m AdProfileMembers) Validate(formats strfmt.Registry) error {
    var res []error

    for i := 0; i < len(m); i++ {

        if swag.IsZero(m[i]) { // not required
            continue
        }

        if m[i] != nil {

            if err := m[i].Validate(formats); err != nil {
                if ve, ok := err.(*errors.Validation); ok {
                    return ve.ValidateName(strconv.Itoa(i))
                }
                return err
            }
        }

    }

    if len(res) > 0 {
        return errors.CompositeValidationError(res...)
    }
    return nil
}
```
However, this function never gets called while validating the parent AdProfile object. This is the generated code that validates the array on the parent object (the array is called Members):
```
func (m *AdProfile) validateMembers(formats strfmt.Registry) error {

    if err := validate.Required("members", "body", m.Members); err != nil {
        return err
    }

    return nil
}
```
It seems to me that this function is missing a call to `m.Members.Validate(formats)`. This would cause us to call validate individually on each of the children in the Members array.

As a side note, the above function is not generated _at all_ if the array field is not a required field. This seems wrong. Even if the array itself is not required, if is provided and there are objects inside it, they should be validated according to their required fields. Right now, this is _not_ happening. 

## Fix

I've confirmed with that we if we add a call to `m.Members.Validate(formats)` here, we will correctly validate the children objects (AdProfileMembersItems):
```
func (m *AdProfile) validateMembers(formats strfmt.Registry) error {

    if err := validate.Required("members", "body", m.Members); err != nil {
        return err
    }

    if err := m.Members.Validate(formats); err != nil {
        return err
    }

    return nil
}
```
Posting to the API with bad data produces the expected output:
```
{\"code\":602,\"message\":\"allow_pending_creatives in body is required\"}
```

## Environment
swagger version: 0.10.0  
go version: 1.8
OS: Linux Ubuntu
