### ISSUE TITLE
Multiple required authentication types

### ISSUE THREAD

**Issue by Crevil** [go-swagger/go-swagger#1201]
## Problem statement
When defining multiple required authentication mechanisms only one of them is invoked.
According to [Swagger spec 2](https://swagger.io/docs/specification/2-0/authentication/#multiple) the following definition requires both mechanisms to be invoked.

## Swagger specification

```yaml
securityDefinitions:
  authorizationToken:
    type: apiKey
    name: Authorization
    in: header
  deviceId:
    type: apiKey
    name: X-DeviceId
    in: header
security:
  - authorizationToken: []
    deviceId: []
```

## Steps to reproduce
Generate server implementation with two required security types (like the above YAML).
Implement a log statement in each of the handlers and perform a request to a secured endpoint.
Only one of the handlers will be invoked and output a log.

## Environment
swagger version: 0.12.0
go version: 1.9.0
OS:   Apple macOS Sierra 10.12.6
