### ISSUE TITLE
Enum array doesn't generate a constant

### ISSUE THREAD

**Issue by alexDrinkwater** [go-swagger/go-swagger#1203]
## When generating model, enum arrays do not generate a constant for the enum.

I expected a constant to be generated for an enum array of strings like it is when generating and enum that is not an array. 

## Swagger specification
A constant should be created for roles in the below spec:
```
  foo:
    type: object
    properties:
      name:
        type: string
      organizationId:
        format: int32
        type: integer
      roles:
        type: array
        items:
          type: string
          enum:
            - Admin
            - User
            - SuperAdmin
```

## Environment
swagger version: 0.11.0 
go version: 1.8
OS:   OSX
