### ISSUE TITLE
Could we add bson + json into model

### ISSUE THREAD

**Issue by xuanzhaopeng** [go-swagger/go-swagger#1227]
## Problem statement

When using swagger to generate models, it will generate
```go
type Item struct {
	// product code
	ProductCode string `json:"productCode,omitempty"`
}
```

But however,  I want to read mongo data directly into this Item, the attribute in Mongo is also called "productCode", however I cannot. 

Because it will try to find "productcode" (lowercase) instead of "productCode". Is it possible we could add bson flag also in the descriptions? 

## Environment
swagger version: 0.12.0 
go version: 1.18
OS:  Mac OS

**Comment by casualjim** [comment]
you can use another annotation in your spec to provide extra struct tags

for example:

```yaml
type: object
properties:
  productCode:
    type: string
    x-custom-tag: "bson:\"productCode\" proto:\"product_code\""
```

**Comment by greenpau** [comment]
@casualjim , I am running into the same issue.

In MongoDB the field is "sys_name". When un-marshaling data from the database, my app looses all the fields with underscores in them.

I tried adding `x-custom-tag`:

```
  SnmpProperties:
    properties:
      SysName:
        type: string
        x-custom-tag: "bson:\"sys_name\""
      SysObjectId:
        type: string
    type: object
```

However, the resulting Go struct does not have `bson`:

```golang
// SnmpProperties snmp properties
// swagger:model SnmpProperties
type SnmpProperties struct {

    // sys name
    SysName string `json:"SysName,omitempty"`

    // sys object Id
    SysObjectID string `json:"SysObjectId,omitempty"`
}
```

The desired struct is:

```golang
// SnmpProperties snmp properties
// swagger:model SnmpProperties
type SnmpProperties struct {

    // sys name
    SysName string `json:"SysName,omitempty" bson:"sys_name,omitempty"`

    // sys object Id
    SysObjectID string `json:"SysObjectId,omitempty" bson:"sys_name,omitempty"`
}
```
