### ISSUE TITLE
example annotation only supports strings

### ISSUE THREAD

**Issue by billneff79** [go-swagger/go-swagger#1268]
## Problem statement

I can only create `string` examples for model/param elements using the `example:` annotation.  I would like to be able to create array examples, similar to how `enum` works

## Swagger specification
```
type MyModel struct {
	// Array of names
	// example:  name1,name2
	Names []string `json:"names"`
}
```

**current generated**
```
 names:
                description: Array of names
                example: "name1,name2"
                type: array
                x-go-name: Names
                items:
                  type: string
```

**desired generated**
```
 names:
                description: Array of names
                example: 
                - name1
                - name2
                type: array
                x-go-name: Names
                items:
                  type: string
```

## Environment
swagger version: 2.0.0
go version:  go1.9.2 darwin/amd64
OS:   Mac OS
