### ISSUE TITLE
can't compile generated server code for "file" in requests

### ISSUE THREAD

**Issue by koron** [go-swagger/go-swagger#1330]
## Problem statement

After [this change](https://github.com/go-swagger/go-swagger/commit/42a38c26361b19a5fbcceb1621af9ee920c5a4ad#diff-404f36d691a324fb842e85a813e5735a), `type: file` parameters become to be converted to `io.ReadCloser` (before `runtime.File`)
But generated code for `BuildRequest()` keeps using `runtime.File` (not pointer) at [here](https://github.com/go-swagger/go-swagger/blob/894e78ba153c4b31bc2f34e33a016a7a91c0842c/generator/templates/server/parameter.gotmpl#L168).
This causes compilation errors like this.

    cannot use runtime.File literal (type runtime.File) as type io.ReadCloser in assignment:
            runtime.File does not implement io.ReadCloser (Close method has pointer receiver)

Smallest input example:

```yaml
    post:
      operationId: UploadFile
      description: Upload a new file
      parameters:
        - name: fileBody
          in: formData
          type: file
          required: true
```

I remove [`.IsNullable` check](https://github.com/go-swagger/go-swagger/blob/894e78ba153c4b31bc2f34e33a016a7a91c0842c/generator/templates/server/parameter.gotmpl#L168) and force to append `&` on local.
It works good for me, but I think this my solution is not good for others.
How should it be fixed?
