### ISSUE TITLE
[feedback] format mac does not work in swagger:strfmt

### ISSUE THREAD

**Issue by allencloud** [go-swagger/go-swagger#1348]
## Problem statement

I ran into an issue that I wish swagger could help me to validate MAC address in struct defined in swagger.yml, like:

```
      MacAddress:
        description: "MAC address of the container."
        type: "string"
        format: mac
```
Then the generated struct has a validation function to validate the mac format of this field.

However it fails.

Could we support this feature in go-swagger?

## Environment
swagger version: `version: 0.12.0`
go version: `go version go1.9.1 darwin/amd64` 
OS:
