### ISSUE TITLE
Schema does not initialize defaults in nested objects

### ISSUE THREAD

**Issue by fredbi** [go-swagger/go-swagger#1393]
## Problem statement
Whenever a schema declares a default value, the corresponding generated structure is properly initialized, like in:
```yaml
parameters:
  - in: body
    name: myBodyParam
    schema:
      type: object
      properties:
        p1: 
          type: string
        p2:
           type: integer
      default:
        p1: abc
        p2: 12
```

However, when defaults are declared at a lower level, no initialization takes place, as in:
```yaml
parameters:
  - in: body
    name: myBodyParam
    schema:
      type: object
      properties:
        p1: 
          type: string
          default: abc
        p2:
          type: integer
          default: 12
```

It looks like the "schema" term used in the [json schema spec](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-6.2) has been taken to the letter, making it equivalent to the swagger schema term.

## Steps to reproduce
generate server with structures proposed  as examples and submit uninitialized body

## Environment
swagger version: x.x.x  
go version: x.x.x  
OS:
