### ISSUE TITLE
Enhancement: Add constructor functions for model types

### ISSUE THREAD

**Issue by dmjones500** [go-swagger/go-swagger#1417]
## Problem statement

Building response objects is difficult due to use of pointers in model structs. This is most noticeable during development/prototyping phase, where hand-crafting response objects is common.

Suggestion - provide a constructor function, `NewFoo(param1, param2...)`, for model types.

## Swagger specification

E.g. Swagger containing the following definition:

```yaml
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
```

Produces a model class:

```go
type ErrorModel struct {
	Code *int32 `json:"code"`
	Message *string `json:"message"`
}
```

which is frustrating to construct by hand with literals due to the use of pointers. One solution is to generate a constructor:

```go
func NewErrorModel(code int32, message string, someOptionalField *type) {
  ...
}
```

Optional fields would still need to be represented as pointers, but required fields could take non-pointer types. In many cases this will simplify construction of these types.

## Environment
swagger version: 0.13.0
