### ISSUE TITLE
Useless error message 'json: cannot unmarshal bool into Go struct field SwaggerProps.paths of type []string' at swagger generate client

### ISSUE THREAD

**Issue by attila123** [go-swagger/go-swagger#1425]
## Problem statement
'swagger generate client -f swagger.json' results in a useless error message:
json: cannot unmarshal bool into Go struct field SwaggerProps.paths of type []string
-> Have no idea what is wrong.

## Swagger specification
Unfortunately this is a proprietary code and therefore I cannot disclose/attach the swagger.json.

## Steps to reproduce
See above.

## Environment
swagger version: 'dev' installed it by 'go get -u github.com/go-swagger/go-swagger/cmd/swagger' on 2018-02-20.
go version: 1.9.4
OS:  Linux

**Comment by fredbi** [comment]
There is indeed much room for improvement with error messages.
See also #1234

**Comment by fredbi** [comment]
and here #121 
and also here #1308 
...

**Comment by casualjim** [comment]
This implies that the json is invalid but the golang json library doesn't give us a lot of info.

**Comment by adsodemelk** [comment]
I hit this problem while running a swagger.yml api definition. my workaround was to convert it to swagger.json and re run go-swagger.

**Comment by gregmarr** [comment]
Do you have anything with any of these names?  If so, then they must be quoted or yaml considers them booleans: y, yes, n, no, true, false, on, off

**Comment by juacker** [comment]
Maybe not your scenario, but I had the same problem with a swagger definition similar to this one:

```
InputMessageParams:
  type: object
  properties:
    key1:
      type: string
      required: true
    key2:
      type: string
      required: true
    key3:
      type: string
      required: true
```

I replaced with this and worked:

```
InputMessageParams:
  type: object
  required:
    - key1
    - key2
    - key3
  properties:
    key1:
      type: string
    key2:
      type: string
    key3:
      type: string
```
