### ISSUE TITLE
Simple aliased model type does not validate format

### ISSUE THREAD

**Issue by fredbi** [go-swagger/go-swagger#1437]
## Problem statement
When redefining a type with format like in:
```
definitions:
  aDate:
    type: string
    format: date
```

Posting a small PR to fix this _and only this_

The generated model for aDate has empty Validate() method
## Environment
swagger version:  current master
go version: x.x.x  
OS:
