### ISSUE TITLE
Ability to define custom property type

### ISSUE THREAD

**Issue by romanyx** [go-swagger/go-swagger#1467]
## Problem statement
Is there ability to define custom property type? In every PATCH request I got a list of non required fields, which I should handle as follows:

1. If field's value in the body is null, I should save null value in DB
2. If field's value in the body is not null, I should save this value in DB
3. If fields value is missing in the body, I shouldn't do anything.

To do this, as defined [here](https://www.calhoun.io/how-to-determine-if-a-json-key-has-been-set-to-null-or-not-provided/) I should define type like this, with custom unmarshalling.

``` go
type JSONInt struct {
  Value int
  Valid bool
  Set   bool
}

func (i *JSONInt) UnmarshalJSON(data []byte) error {
  // If this method was called, the value was set.
  i.Set = true

  if string(data) == "null" {
    // The key was set to null
    i.Valid = false
    return nil
  }

  // The key isn't set to null
  var temp int
  if err := json.Unmarshal(data, &temp); err != nil {
    return err
  }
  i.Value = temp
  i.Valid = true
  return nil
}
```

But how could I set custom property type in my model definition?

``` yaml
title: Stock request
type: object
properties:
  name:
    description: Stock name
    type: JSONString
  status:
    description: Status of a stock
    type: JSONInt
```

**Comment by fredbi** [comment]
The "type" keyword refers to valid JSON-schema types.
If you want to construct a custom object type, you would define as schema for such an object then reuse it with "$ref" afterwards.

Now if you want to define a complete custom object with custom serialization etc..., you may use the "x-go-type" extension: go-swagger does not generate anything there and reuse your type in definitions.

**Comment by romanyx** [comment]
@fredbi Thanks! I couldn't found examples of using `x-go-type` in properties, and only few mentions of it in docs at all, can you please provide an example of it?

**Comment by fredbi** [comment]
Have a look there https://github.com/go-swagger/go-swagger/blob/master/fixtures/codegen/existing-model.yml#L84-L88

**Comment by romanyx** [comment]
Does following swagger spec:

```yaml
title: Stock request
type: object
properties:
  name:
    description: Stock name
    x-go-type:
      type: JSONString
  status:
    description: Status of an stock
    x-go-type:
      type: JSONInt
```

Should be generated into this?

```go
// StockRequest Stock request
//
// swagger:model StockRequest
type StockRequest struct {

	// Stock name
	Name JSONString `json:"name,omitempty"`

	// Status of an stock
	Status JSONInt `json:"status,omitempty"`
}
```

Because I'm having `interfaces{}` as types.
