### ISSUE TITLE
No validation is called when the object referring to the array type parameter

### ISSUE THREAD

**Issue by johnliu26** [go-swagger/go-swagger#1537]
## Problem statement
The issue is similar to the Issue #1392 and #1093 but not the same.
When the body parameter is an under properties in object type, referencing array data type, none of the validation is called. But if we mark the body parameter required, the validation will show in the auto-generated code.

## Swagger specification
**Case : 1**
```yaml
profileCfg: 
           type: object
           properties:
               value1:
                   type: integer
                   format: int32
              value2:
                  type: integer
                  format: int32                    
profileCfgs:
           type: array
           x-omitempty: true
           items:
              $ref: '#definitions/profileCfg'
Profile:
           type: object
           properties: 
                  profileCfg:
                       $ref: '#definitions/profileCfgs'
```

**Case: 2**
```yaml
profileCfg: 
           type: object
           properties:
               value1:
                   type: integer
                   format: int32
              value2:
                  type: integer
                  format: int32                    
profileCfgs:
           type: array
           x-omitempty: true
           items:
              $ref: '#definitions/profileCfg'
Profile:
           type: object
           required:
               - profileCfg
           properties: 
                  profileCfg:
                       $ref: '#definitions/profileCfgs'
```

**Case 3**

```yaml
profileCfg: 
           type: object
           properties:
               value1:
                   type: integer
                   format: int32
              value2:
                  type: integer
                  format: int32            
Profile:
           type: object
           required:
               - profileCfg
           properties: 
                  profileCfg:
                       type: array
                       x-omitempty: true
                       items:
                         $ref: '#definitions/profileCfg'
```
                    
## Steps to reproduce

Generate the server based on this swagger
In the Case1, the validation will not be generated.

```go
func (m *Profile) Validate(formats strfmt.Registry) error {
        var res []error
        if len(res) > 0 {
                              return errors
        }
         return nil
}
```

In the Case2, the validation will be generated successfully.

```go
func (m *profile) Validate(formats strfmt.Registry) error {
      var res []error
      if err := m.validateProfile(formats); err != nil {
                res = append(res, err)
      }
     if len(res) > 0 {
                              return errors
        }
         return nil
}
```

In the Case3, if we remove the refer to the array struct, and without mark the area required the validation will still be generated same as the code in the Case 2. (Case 3 validation generation is by the fix in the issue #1392 and #1093.

So I think there may an issue that I have to mark the parameter required which it referring to the array struct if I want the validation to generate. Thanks very much for your help!

## Environment
swagger version: 0.13.0
go version: go1.10.2 linux/amd64
OS:  Linux Centos
