### ISSUE TITLE
Question: nullable elements in slices and maps

### ISSUE THREAD

**Issue by fredbi** [go-swagger/go-swagger#1561]
## Problem statement

I observe that slices and maps elements are nullable only when referring to a complex element (i.e. len(properties)>0) or to an explicitly x-nullable element.

I observe too that we have some specific rules to render primitive types as pointers (based on validations and default).

When these rules apply, however, I am facing some inconsistencies between the composed type (e.g. []int64 or map[string]int64) and the element type (e.g. *int64).

Everything works well until I decide, for instance to set a "minimum: 0" validation on the element.

At this point, the element type is a pointer and the map / slice type thinks its element is not a pointer...
resulting in broken codegen.

Everything works fine again if I specify x-nullable (everyone agree this is a pointer then...).

I could work around this in dev, resolving primitive pointers as pointers in slices and maps, but found out this breaks the PointerLifting test, which assumes this should never be the case.

Is there any particular reason why this test assumes we never want pointers as elements?

## Swagger specification
Here are two examples:
```yaml
definitions:
  aSlice:
    type: array
    items:
     type: integer
     minimum: 0
  aMap:
    type: object
    additionalProperties:
      type: integer
      minimum: 0
```
## Environment
swagger version: x.x.x  
go version: x.x.x  
OS:
