### ISSUE TITLE
Models: Invalid pointer redirect

### ISSUE THREAD

**Issue by sajal** [go-swagger/go-swagger#1562]
## Problem statement

Generated code includes incorrect pointer operation.

```go
// GroupPreference group preference
// swagger:model groupPreference
type GroupPreference map[string]float32

// Validate validates this group preference
func (m GroupPreference) Validate(formats strfmt.Registry) error {
	var res []error
	for k := range m {
		if swag.IsZero(m[k]) { // not required
			continue
		}
		if err := validate.Minimum(k, "body", float64(*m[k]), -5, false); err != nil {
			return err
		}
		if err := validate.Maximum(k, "body", float64(*m[k]), 5, false); err != nil {
			return err
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
```

`*m[k]` causes compiler error `invalid indirect of m[k] (type float32)`. It should be `m[k]`

## Swagger specification

The swagger definition is :-

```yaml
  groupPreference:
    type: object
    additionalProperties:
      type: number
      format: float
      minimum: -5
      maximum: 5
    example:
      default: 0
      CN: -0.2
      GB: 0.5
      NL: -5
```

`format: float` or `format: double`, both have the same issue.

## Steps to reproduce

swagger generate client -f spec_containing_definition.yaml -t $GOPATH/github.com/user/repo

## Environment
swagger version: 0.14.0  
go version: go version go1.10 linux/amd64
OS:  Linux 4.13.0-41-generic #46-Ubuntu SMP
