### ISSUE TITLE
Required properties with x-nullable:true cannot accept null values

### ISSUE THREAD

**Issue by akhobov** [go-swagger/go-swagger#1601]
## Problem statement
In order to ensure that a field is included into responses (doesn't have `omitempty` struct field attribute) it should be listed in the required array. On the other hand if the same field can be `null` it should have `x-nullable: true` property set. This works fine for GET requests. However the field validation on POST/PUT requests considers the `null` value as invalid that leads to an error as follows:

```
{
    "code": 602,
    "message": "field in body is required"
}
```
 
It seems the culprit is the following code in the validateField() function that checks that a not default value is provided:
```
   if err := validate.Required("field", "body", m.Field); err != nil {
          return err
      }
```

The Swagger Specification 2.0 stipulates that the `required` property is taken directly from the JSON Schema definition and follows the same specifications. The [JSON Schema Validation](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.4.3) document states the following:
> 5.4.3.2.  Conditions for successful validation
>
>   An object instance is valid against this keyword if its property set
>   contains all elements in this keyword's array value.

Correct me if I'm wrong but it doesn't state that properties should have certain values. Only that properties should be present in an object instance. This matches the `omitempty` attribute logic but not that validation code. 

## Swagger specification
```
  definitions:
    foo:
      type: object
      required:
        - field
        - bar
      properties:
        field:
          type: string
          x-nullable: true
        bar:
          type: object
          x-nullable: true
          required:
            - baz
          properties:
            baz:
              type: string
```

## Steps to reproduce
1. Generate server
1. Run it
1. Send POST or PUT request with an object that has the field set to `null`

## Environment
swagger version: 0.13.0  
go version: 1.10.2
OS: Linux
