### ISSUE TITLE
Proposal: x-omitempty for general types

### ISSUE THREAD

**Issue by zhuangqh** [go-swagger/go-swagger#1623]
## Problem statement

Currently, we use `x-omitempty` to exclude null array value. related PR #1189 
Maybe `x-omitempty` can support general type to control the `omityempty` tag.

```yaml
Foo:
  type: "object"
  properties:
    hasOmitEmptyTrue:
      type: string
      x-omitempty: true
    hasOmitEmptyFalse:
      type: string
      x-omitempty: false
```
produce
```go
type Foo struct {
	// has omit empty false
	HasOmitEmptyFalse string `json:"hasOmitEmptyFalse"`
	// has omit empty true
	HasOmitEmptyTrue string `json:"hasOmitEmptyTrue,omitempty"`
}
```

## Environment
swagger version: x.x.x  
go version: x.x.x  
OS:
