### ISSUE TITLE
[Bug] Order in logical AND security definition not honored

### ISSUE THREAD

**Issue by someone1** [go-swagger/go-swagger#1687]
## Problem statement

I have randomly been seeing `nil` principals for API methods generated in go-swagger where there shouldn't be and it changes randomly on compile (e.g. if I run the API Server 5 times, 2 of those times I'll have no issues, and the other 3 I'll experience `nil` principals in 3 DIFFERENT API endpoints).

My API requires both an API Key and Oauth2 security for all endpoints, where only the latter can generate a proper principal object, the former just validates the key and returns a `nil` principal. The order of the security definition in the YAML file is reflective of this need.

My guess is that the security definition is placed into a Go `map` and then iterated over which doesn't guarantee order when validating the incoming request.

@casualjim was able to confirm this in the Slack channel, some relevant comments of his ([discussion link](https://goswagger.slack.com/archives/C04R30YMU/p1536335982000100)):

> it can be fixed by fixing the 2 places where we use those and have a different (un)marshaller
> this line is your problem: https://sourcegraph.com/github.com/go-openapi/runtime@master/-/blob/middleware/router.go#L150
> together with: https://github.com/go-openapi/spec/blob/master/swagger.go#L85
> https://github.com/go-openapi/spec/blob/master/operation.go#L35

## (Relevant) Swagger specification

```yaml
securityDefinitions:
 api_key:
   type: "apiKey"
   name: "key"
   in: "query"
 google_id_token:
   authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth"
   flow: "implicit"
   type: "oauth2"
   x-google-issuer: "https://accounts.google.com"
   x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
security:
  - api_key: []
    google_id_token: []
```

## Steps to reproduce

(see above)

## Environment
go-swagger version: tip
go version: 1.10.1 
OS:   Ubuntu 18.04
