### ISSUE TITLE
How to specify body definition without additional level of nesting?

### ISSUE THREAD

**Issue by moskal91** [go-swagger/go-swagger#1716]
## Problem statement
How to specify body parameter without name? Generated code for provided example does not allow for

```
PUT /user/1234/activation
{
   "active": true,
}
```

server returns error

```
{
   "code": 400
   "message": "parsing body body from \"\" failed, because json: cannot unmarshal string into Go struct field ActivateUserBody.active of type bool"
}
```

when i try:

```
PUT /user/1234/activation
{
   "activateuserbody": {
       "active": true
    }
}
```

everything works ok.

## Swagger specification
```yml
swagger: '2.0'
info:
  description: Body parameters
  title: App
  version: 1.0.0
paths:
  '/user/{user_id}/activation':
      put:
        operationId: activateUser
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - in: path
            name: user_id
            required: true
            description: User ID
            type: string
          - in: body
            name: activation
            description: Body
            required: true
            schema:
              type: object
              properties:
                active:
                  type: boolean
        responses:
          '200':
            description: OK
        summary: Activate user
```

## Environment
swagger version: 0.6.0
go version: 1.11
OS: Ubuntu 18.04

**Comment by casualjim** [comment]
can you share a project with the issues you encounter? 

The behavior you see is not what others are seeing so I want to take a look at your poject. This might be the result of flattening or something

**Comment by moskal91** [comment]
Unfortunately it is private project, but I just generated clean server from above example with `swagger generate server -f swagger.yml` and result is exactly the same:

```shell
$ ./app-server --port 2002
2018/09/20 17:49:12 Serving app at http://127.0.0.1:2002

$ http PUT localhost:2002/user/1234/activation active=true
HTTP/1.1 400 Bad Request
Content-Length: 162
Content-Type: application/json
Date: Thu, 20 Sep 2018 15:49:30 GMT

{
    "code": 400,
    "message": "parsing activation body from \"\" failed, because json: cannot unmarshal string into Go struct field ActivateUserBody.active of type bool"
}

$ http PUT localhost:2002/user/1234/activation activation.active=true
HTTP/1.1 501 Not Implemented
Content-Length: 55
Content-Type: application/json
Date: Thu, 20 Sep 2018 15:49:38 GMT

"operation .ActivateUser has not yet been implemented"
```

My `Gopkg.toml`:
```toml
[[constraint]]
  name = "github.com/go-openapi/errors"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/loads"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/runtime"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/swag"
  version = "0.16.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
```
