### ISSUE TITLE
Generate go structs with tag `json:"-"`

### ISSUE THREAD

**Issue by cozzbp** [go-swagger/go-swagger#1731]
## Problem statement

If you have code being generated from swagger, and want a field to be omitted when marshalling, it would make sense to be able to do that like so:
```
      id:
        type: string
        x-go-custom-tag: json:"-"
        x-nullable: true
```

This generates something like so:

```
// id
ID *string `json:"id,omitempty" json:"-"`
```

The only way I've gotten this to work, is to do something like

```
      "-":
        type: string
        x-go-name: id
        x-nullable: true
```

But this only works if there is one field you want omitted.

Any ideas?

## Environment
swagger version: 0.16.0  
go version: 1.11
OS:   Linux/Ubuntu
