### ISSUE TITLE
generated code changes the order of properties in struct

### ISSUE THREAD

**Issue by Tron2016** [go-swagger/go-swagger#1759]
Define in swagger yaml:

```yaml
Product:
    type: "object"
    properties:
      product_id:
        type: "string"
      name:
        type: "string"
```
Generated by "swagger generate server":
```go
type Product struct {
	Name string `json:"name,omitempty"`
	ProductID string `json:"product_id,omitempty"`
}
```
I want product_id be the first property of Product struct. 
Is there any way to keep the order of properties?
