### ISSUE TITLE
Why generating *string for string fields in the model? 

### ISSUE THREAD

**Issue by ok11** [go-swagger/go-swagger#1766]
Not really an issue, rather a question. What is the motivation to generate pointers to string in models rather then strings? It enforces to implement funny dereferencing that may be also not always safe. And, frankly, I do not see a big benefit in this approach. So -- why?

For example, the following spec 
```
type: object
properties:
  code:
    type: string
    description: "Error code"
    example: RESOURCE_NOT_FOUND
  message:
    type: string
    description: "Error message"
    example: "Requested resource not found"
  target:
    type: string
    description: "Related resource"
    example: "/products/42"
  details:
    type: object
    properties:
      code:
        type: string
        description: "Detailed error code"
        example: "MongoDB:2038"
      message:
        type: string
        description: "Detailed error message"
        example: "MongoDB: no document with ObjectID 42"
    required:
      - code
      - message
required:
  - code
  - message

```

results in (fragment)
```
type Error struct {

	// Error code
	// Required: true
	Code *string `json:"code"`

	// details
	Details *ErrorDetails `json:"details,omitempty"`

	// Error message
	// Required: true
	Message *string `json:"message"`

	// Related resource
	Target string `json:"target,omitempty"`
}

```
`Code *string` looks somehow weird, doesn't it?
