### ISSUE TITLE
One spec in multiple files (data types logic override) - error of generating

### ISSUE THREAD

**Issue by SArtemJ** [go-swagger/go-swagger#1767]
## Problem statement
runtime error - when try to generate spec with several files
## Swagger specification
For example i separate one file to several minimal files
api.swagger.yaml
```
---
swagger: '2.0'
info:
  version: "1.0.0"
  title: FHIR API
  description: |
    #### FHIR API
schemes:
- http
host: "fhir.test.lan"
basePath: /

parameters:
  patientID:
    name: patientID
    in: path
    description: "patient ID"
    type: string
    required: true

paths:
  /Patient/{patientID}:
    parameters:
    - $ref: "#/parameters/patientID"
    get:
      tags:
      - fhir
      produces:
      - application/fhir+json
      consumes:
      - application/fhir+json
      responses:
        200:
          $ref: "#/responses/Patient"
    put:
      tags:
      - fhir
      produces:
      - application/fhir+json
      consumes:
      - application/fhir+json
      responses:
        200:
          $ref: "#/responses/Patient"

responses:
  Patient:
    description: "Patient"
    schema:
      allOf:
      - $ref: 'Patient.yaml'
```

Object (patient) describes in different file
Patient.yaml
```
type: object
title: "Info about patient"
description: ""
properties:
      id:
        type: string
      identifier:
        type: array
        description: "Identifier"
        items:
            allOf:
            - $ref: 'Identifier.yaml'
      active:
        type: boolean
      name:
        description: "Name"
        type: string
required:
- name
```
Patient has Identifier which exist in another file
Identifier.yaml
```
type: object
title: "Identifier"
description: "v3.1.0-12545"
properties:
  use:
    type: string
    example: "usual"
    enum:
    - "usual"
    - "official"
    - "temp"
    - "secondary"
    - "old"
  system:
    type: string
  value:
    description: "Some unique value"
    type: string
  assigner:
    description: "Organization"
    allOf:
      - $ref: 'Reference.yaml'
required:
  - use
```

Identifier has field with type Reference which describes like
Reference.yaml
```
type: object
title: "reference"
description: "v3.1.0-12545"
properties:
      reference:
        description: "Literal reference, Relative, internal or absolute URL"
        type: string
        example: "literal reference"
      identifier:
        description: "Logical reference, when literal reference is not known"
        allOf:
        - $ref: 'Identifier.yaml'
      display:
        type: string
        description: "Text alternative for the resource"
```
One interesting thing than Reference has one field type of Identifier
all types in this example equal logic data types of FHIR format

## Steps to reproduce
let's try to generate server
```
swagger generate server -f ./api.swagger.yaml --with-flatten=full --exclude-main
```

return error
```
2018/10/23 19:11:35 validating spec /Users/aj/go/src/awesomeProject3/api.swagger.yaml
2018/10/23 19:11:35 preprocessing spec with option:  full flattening
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1a0 pc=0x13ad539]

goroutine 1 [running]:
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/analysis.(*AnalyzedSchema).initializeFlags(0xc4207fce00)
        /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/analysis/schema.go:213 +0x29
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/analysis.Schema(0x0, 0x16f1880, 0xc42116e700, 0xc420784bc0, 0x31, 0x0, 0xc420d8bc80, 0x0, 0x0)
        /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/analysis/schema.go:25 +0xa2
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/analysis.namePointers(0xc421196090, 0xc4215436b0, 0x138d369)
        /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/analysis/flatten.go:1317 +0xec9
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/analysis.stripPointersAndOAIGen(0xc421196090, 0x0, 0x0)
        /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/analysis/flatten.go:1130 +0x2f
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/analysis.Flatten(0xc420254000, 0x0, 0xc420784bc0, 0x31, 0x10000, 0x0, 0x0)
        /go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/analysis/flatten.go:182 +0x31a
github.com/go-swagger/go-swagger/generator.validateAndFlattenSpec(0xc4204ba400, 0xc42085ba40, 0xc420784bc0, 0x31, 0xc42085ba40)
        /go/src/github.com/go-swagger/go-swagger/generator/shared.go:1073 +0x1dc
github.com/go-swagger/go-swagger/generator.newAppGenerator(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4204ba400, 0xc4204c0120, ...)
        /go/src/github.com/go-swagger/go-swagger/generator/support.go:92 +0x162
github.com/go-swagger/go-swagger/generator.GenerateServer(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4204ba400, 0xc4202b89c0, ...)
        /go/src/github.com/go-swagger/go-swagger/generator/support.go:39 +0x94
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Server).generate(0xc420696680, 0xc4204ba400, 0x0, 0x0)
        /go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/server.go:86 +0x94
```

Maybe this datatypes looks like something strange
Patient -> Identifier -> Reference -> Identifier - but this is standard
When all datatypes describes in one swagger file - all works ok but for more usability need to separate by several files
If in Reference description change type 'Identifier.yaml' for example - on string type - all generated good

How it can be fixed?
Thanks!

## Environment
swagger version: 0.16.0
go version: 1.10.3
OS:  mojave 10.14

**Comment by fredbi** [comment]
interesting use case. Looks like a bug in go-openapi/analysis to flatten this spec.

You could try moving your ext references from responses to definitions, it might help.

**Comment by fredbi** [comment]
Mmhhh. Tried to play a bit with this spec.

Problem lays with circular ref formed by several files. We still have a problem in go-openapi/spec with such circulars.

Try defining the cycle in one single file.

**Comment by SArtemJ** [comment]
> Mmhhh. Tried to play a bit with this spec.
> 
> Problem lays with circular ref formed by several files. We still have a problem in go-openapi/spec with such circulars.
> 
> Try defining the cycle in one single file.

If i describe "Patient" object in "definitions" zone then i get error 
```
is invalid against swagger specification 2.0. see errors :
- definitions.Patient.schema in body is a forbidden property
```
Because one schema using in body and in responses

So in Identifier.yaml i set the value for reference type like full description object
```
type: object
title: "Identifier"
description: "v3.1.0-12545"
properties:
  use:
    type: string
    example: "usual"
    enum:
    - "usual"
    - "official"
    - "temp"
    - "secondary"
    - "old"
  type:
    description: "Identifier type"
    allOf:
      - $ref: 'CodeableConcept.yaml'
  system:
    type: string
    example: "urn:oid:1.2.36.146.595.217.0.1"
  value:
    description: "Some unique value"
    type: string
  period:
    description: "Time"
    allOf:
      - $ref : 'Period.yaml'
  assigner:
    description: "Organization"
    type: object
    title: "reference"
    description: "v3.1.0-12545"
    properties:
          reference:
            description: "Literal reference, Relative, internal or absolute URL"
            type: string
            example: "literal reference"
          identifier:
            description: "Logical reference, when literal reference is not known"
            type: array
            items:
              allOf:
              - $ref: 'Identifier.yaml'
          display:
            type: string
            description: "Text alternative for the resource"
required:
  - use
```

But when i'm trying to generate - return's me same runtime error
