### ISSUE TITLE
Unused variable i

### ISSUE THREAD

**Issue by vburenin** [go-swagger/go-swagger#1771]
## Problem statement
Generated code has unused variable 'i' in a for loop statement
```Go
// bindKeys binds and validates array parameter Keys from query.
//
// Arrays are parsed according to CollectionFormat: "multi" (defaults to "csv" when empty).
func (o *GetDataParams) bindKeys(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("keys", "query")
	}

	// CollectionFormat: multi
	keysIC := rawData

	if len(keysIC) == 0 {
		return errors.Required("keys", "query")
	}

	var keysIR []string
	for i, keysIV := range keysIC {
		keysI := keysIV

		keysIR = append(keysIR, keysI)
	}

	o.Keys = keysIR

	return nil
}
```

## Steps to reproduce
```yaml
    get:
      summary: retrieves a batch of key data
      tags:
      - kv
      operationId: getData
      parameters:
      - name: keys
        description: a list of keys to retrieve data for
        in: query
        type: array
        required: true
        items:
          minItems: 1
          maxItems: 10
          type: string
        collectionFormat: multi
```
## Environment
swagger version: git hash 471eb80
go version: 1.11.1
OS: macos
