### ISSUE TITLE
Add support for types of the new mongo-go-driver

### ISSUE THREAD

**Issue by karlTGA** [go-swagger/go-swagger#1854]
## Problem statement

It is complicated to use a model with the new official mongo-go-driver. At this moment I work around that problem with the `x-go-type` flag. 

``` yaml
  ObjectId:
    type: string
    example: 507f1f77bcf86cd799439011
    x-go-type:
      import: 
        package: github.com/mongodb/mongo-go-driver/bson/objectid
      type: ObjectID

  MongoTimeStamp:
    type: string
    example: "0001-01-01T00:00:00Z"
    x-go-type:
      import: 
        package: time
      type: Time
```
But that leads to two problems. First I have to remove all validate functions for those types and second in the `server.go` the time package is imported twice. 

## Environment
swagger version: 2.0
go-swagger version: 0.17.2
go version: 1.9.2
OS: linux/amd64
