### ISSUE TITLE
Property named validate conflicts with Validate function

### ISSUE THREAD

**Issue by markpeek** [go-swagger/go-swagger#1857]
## Problem statement
While generating a client, an API with an object property of "validate" will produce this golang error message while compiling:

```models/item.go:23:6: type Item has both field and method named Validate```

This occurred in a larger and existing swagger specification/implementation. I reduced this to a simpler example.

## Swagger specification
```
swagger: '2.0'
info:
  version: 0.0.1
  title: test
paths:
  /:
    get:
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
definitions:
  item:
    type: object
    properties:
      validate:
        type: boolean
```
## Steps to reproduce
Code generated in models/item.go
```
...
// Item item
// swagger:model item
type Item struct {

        // validate
        Validate bool `json:"validate,omitempty"`
}

// Validate validates this item
func (m *Item) Validate(formats strfmt.Registry) error {
        return nil
}
...
```

## Environment
swagger version:  v0.18.0  
go version: go version go1.11.1 darwin/amd64
OS:  MacOSX

**Comment by fredbi** [comment]
A workaround for this is to add `x-go-type` to rename the generated field.

A possible enhancement is to detect such conflicts at codegen time. There are still many silent small issues like this where it is possible to break the generated code with reserved names (like if you maliciously name a field `unmarshalBinary`, this also wrecks the code.

**Comment by jeffreydwalter** [comment]
@fredbi where does `x-go-type` go? Is this something that goes in the swagger API spec JSON?

**Comment by fredbi** [comment]
@jeffreydwalter 

Yes. Something like this:
```yaml
definitions:
  UserRepresentation:
    x-go-type:
      type: UserRepresentation
      import:
        package: github.com/fredbi/go-xxxxservice/admin/keycloak/models
    type: object
    properties:
      id:
        type: string
        format: uuid
```
