### ISSUE TITLE
How to customize swagger semantics validate

### ISSUE THREAD

**Issue by chuantianc** [go-swagger/go-swagger#1862]
## Problem statement
How to achieve customize validation? For example, the swagger definitions like this

```yaml
definitions:
  Resources:
    type: "number"
    maximum: 10
    minimum: 0
```
when run the command: swagger validate demo.yaml
I want to check:
+ maximum is larger than minimum
+ maximum must smaller than 20
+ Resources must be plural
+ and so on

## Environment
swagger version: 0.18.0  
go version: 1.11.4  
OS:   mac os
