### ISSUE TITLE
Is "GUID" a special keyword ?

### ISSUE THREAD

**Issue by zhoub** [go-swagger/go-swagger#1864]
## Swagger specification

```
  User:
    type: object
    properties:
      Guid:
        type: string
```

## Steps to reproduce

The example *User* definition has a property called Guid, but the generated the Go struct is
```go
// User user
// swagger:model User
type User struct {

	// Guid
	// Required: true
	GUID *string `json:"Guid"`
}
```

What I wonder is why it's CAMEL-case name not *Guid*, thanks !

## Environment
swagger version: 0.18.0
go version: 1.11
OS:   Windows
