### ISSUE TITLE
validator fails to report path parameters defined defined at operation level

### ISSUE THREAD

**Issue by dolmen** [go-swagger/go-swagger#1866]
## Problem statement

`swagger validate` incorrectly accepts specifications that define path parameters in the operation block instead of the path block.

## Swagger specification

Invalid spec:
```yaml
paths:
  /route/{id}:
    get:
      ...
      parameters:
        name: id
        in: path
        required: true
        type: string
```

Correct spec:
```yaml
paths:
  /route/{id}:
    parameters:
      name: id
      in: path
      required: true
      type: string
    get:
      ...
```

## Environment
swagger version: v0.18.0
go version: 1.11.4  
OS: darwin
