### ISSUE TITLE
Support for parsing property vendor extensions

### ISSUE THREAD

**Issue by fdelayen** [go-swagger/go-swagger#1875]
Hi !

Would be awesome to have support for property vendor extensions !

It would allow more flexibility and is widely supported in the swagger/openAPI community. (For example, by the go-openapi package we rely on here)

For now, this package only supports automatic x-go-name and a few other hard coded extensions, but support for custom extensions would allow people to take control of this.

**Example :**
```
type User struct {
	// the name for this user
        //
        // Extensions:
	// ---
	// x-property-value: value
	// x-property-array:
	//   - value1
	//   - value2
	// x-property-array-obj:
	//   - name: obj
	//     value: field
	// ---
	Name string `json:"name"`
}
```
**Result :**
```
definitions:
  User:
    type: object
      name:
        description: the name for this user
        type: string
        x-property-value: value
        x-property-array:
          - value1
          - value2
        x-property-array-obj:
          - name: obj
            value: field
```
PR incoming 😄 🎁
