### ISSUE TITLE
Swagger mixin with anchors defined in another file.

### ISSUE THREAD

**Issue by jupudibhaskar967** [go-swagger/go-swagger#1928]
## Problem statement

Hi,

I have a use-case where I'm merging multiple swagger specs using "mixin" cli command and I have defined few enums in different files with anchors so that I can reuse those enums across multiple endpoints. But whenever I'm using mixin tool to merge multiple swagger specs, I have 2 problems:

1. The final merged file removed all the anchors in the definitions.
2. Also, the "paths" are appearing before definitions which makes it impossible to refer to anchors and even mixin fails with error - "unknown anchor '<>' referenced".

Can anyone please suggest workaround for this problem?

## Environment
swagger version: 0.18
go version: 1.11
OS: Ubuntu

**Comment by fredbi** [comment]
@ jupudibhaskar967  mixin does not assume you are using YAML.
Anchors are resolved as a preliminary result of YAML unmarshalling and cannot be used in the process that follows.
If you want type re-usability, you should use `$ref` rather than YAML anchors.

**Comment by jupudibhaskar967** [comment]
Is there a way that I can reuse enum types using $ref?

**Comment by casualjim** [comment]
yes there is
file1.yaml
```yaml
definitions:
  severity:
    type: string
    enum: ["low","medium","high"]
```
file2.yaml
```yaml
definitions:
   issue:
     type: object
     properties:
        severity: 
           $ref: "./file1.yaml#/definitions/severity"
```
