### ISSUE TITLE
How to get rid of number suffix while using `allOf`?

### ISSUE THREAD

**Issue by JoeyLuffa** [go-swagger/go-swagger#1941]
I have a base entity:
```
product:
    title: product
    type: object
    properties:
      id:
        title: id
        type: string
        readOnly: true
```
And I also have an extended one:
```
productV1:
    allOf:
      - $ref: "./models.yaml#/definitions/product"
```

However,  when generating go file, the productV1 becomes:

```
type ProductV1 struct {
    ProductV1AllOf0
}

type ProductV1AllOf0 struct {
    id *string
}
```

It adds an additional layer `ProductV1AllOf0` into the `ProductV1` struct. How can I get rid of the additional layer? And I only want all the fields in `product` been injected into `productV1`. How can I achieve this?
