### ISSUE TITLE
Handle multiple header in single callback.

### ISSUE THREAD

**Issue by hyadav5** [go-swagger/go-swagger#1947]
Hiiii..I need to handle multiple header values which are passed from a http request in a single callback function as an argument. Below is my scenario:
**In swagger.yaml file:**
```
securityDefinitions:
  Header1:
    type: apiKey
    name: Authorization
    in: header
  Header2:
    type: apiKey
    name: ResourceIdentifier
    in: header
  Header3:
    type: apiKey
    name: AccountID
    in: header
security:
    - Header1: []
    - Header2: []
    - Header3: []
```

**In generated configure_api.go file:**
```
// Applies when the "Authorization" header is set
api.Header1Auth = func(token string) (interface{}, error) { // Generated with only string argument.
	return nil, errors.NotImplemented("api key auth (Header1) Authorization from header param [Authorization] has not yet been implemented")
}
// Applies when the "resourceIdentifier" header is set
api.Header2Auth = func(token string) (interface{}, error) { // Generated with only string argument.
	return nil, errors.NotImplemented("api key auth (Header2Auth) ResourceIdentifier from header param [Authorization] has not yet been implemented")
}
// Applies when the "AccountID" header is set
api.Header3Auth = func(token string) (interface{}, error) { // Generated with only string argument.
	return nil, errors.NotImplemented("api key auth (Header3Auth) AccountID from header param [Authorization] has not yet been implemented")
}
```

**My requirement is:**
	Callback function are getting gerenated with only single token string as an argument. And I need to fetch all the 3 header values (Authorization, ResourceIdentifier and AccountID) and make a call to my function which take care of my logic authentication. Something like this:
```
//Applies when the "Authorization" header is set
// NEED WITH  ALL ARGUMENT IN SINGLE CALL.
api.BearerAuth = func(Authorization string, ResourceIdentifier string, AccountID string) (interface{}, error) {
	err := app.Handler.Authenticate(Authorization, ResourceIdentifier, AccountID)
	if err != nil {
		return true, err
	}
	return true, nil
}
```

**Is it possible to achieve something like this ?**
