### ISSUE TITLE
Pass OAuth2 scheme name to handler and add it on the request context

### ISSUE THREAD

**Issue by randomjunk** [go-swagger/go-swagger#2041]
## Problem statement

When setting a custom BearerAuthentication function on a generated API spec, the function is always passed `name` as `""` which isn't very useful…

```go
api.BearerAuthenticator = func(name string, auth security.ScopedTokenAuthentication) runtime.Authenticator {
  if name == "myscheme" … // it never will
```

This is because the generated code for `AuthenticatorsFor` is passing `scheme.Name` as the first parameter. But this cannot be provided on an oauth2 scheme as implemented by go-swagger.

The generated code looks like:
```go
func (o *TestAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
    result := make(map[string]runtime.Authenticator)
    for name, scheme := range schemes {
        switch name {
            case "auth_jwt":
                result[name] = o.BearerAuthenticator(scheme.Name, o.AuthJwtAuth)
        }
    }
    return result
}
```

To fix it, either the scheme.Name needs setting somewhere, or else the generated code for AuthenticatorsFor needs to just pass `name` instead.

## Swagger specification

```yaml
paths:
  /admin/function:
    post:
      security:
        - auth_jwt: [ admin ]
securityDefinitions:
  auth_jwt:
    type: oauth2
    authorizationUrl: http://example.com/dummy
    tokenUrl: http://example.com/dummy
    flow: accessCode
    scopes:
      admin: Admin
    description: Auth JWT
```

Trying to add `name: auth_jwt` to this results in:
```
The swagger spec at "swagger.yml" is invalid against swagger specification 2.0. see errors :
- "securityDefinitions.auth_jwt" must validate one and only one schema (oneOf). Found none valid
- securityDefinitions.auth_jwt.name in body is a forbidden property
```

## Steps to reproduce

Generate swagger definitions with oauth2 security.

## Environment
swagger version: v0.19.0
go version: 1.12.7
OS:  --
