### ISSUE TITLE
Add warning messages for inconsistent parameter types and validations

### ISSUE THREAD

**Issue by ilyakaznacheev** [go-swagger/go-swagger#2069]
## Problem statement

The error described in #1951 is hard to track. When you meet her in the code, it's not obvious what the reason is.

It would be very useful to display warnings when the type of parameter does not correspond to the expected validation type (like `minLength` for strings, `mimimum` for numeric and `minItems` for arrays).

## Swagger specification

```yaml
parameters:
  - in: path
    name: id
    required: true
    type: string
    minimum: 1
```

## Steps to reproduce

run `swagger generate server`.

## Environment

swagger version: 0.20.1
go version: 1.12.9 
OS:  macOS 10.14.5
