### ISSUE TITLE
Additional keys in response model

### ISSUE THREAD

**Issue by aeneasr** [go-swagger/go-swagger#2073]
## Problem statement

I would like to have a response which has well-defined fields but which can also include additional (arbitrary keys). I would like go-swagger to both be able to create a client for this model as well as understand Go annotations that express this. Take the following examples for clarification (they all should be the same model): 

```json
{
  "type": "flower",
  "color": "red"
}
```

```json
{
  "type": "animal",
  "legs": 4
}
```

```json
{
  "type": "other",
  "foo": "bar"
}
```

**Comment by fredbi** [comment]
@aeneasr isn't `additionalProperties` be what you are looking for? (notice that `patternProperties`  are not supported).

**Comment by aeneasr** [comment]
Oh, I complteltey missed that annotation - thank you!

**Comment by fredbi** [comment]
Like this:
```yaml
type: object
  properties:
    type: string
  additionalProperties:
    type: string
 ```

or:
```yaml
type: object
  properties:
    type: string
  additionalProperties: true
 ```
