### ISSUE TITLE
Empty string not validated in body schema

### ISSUE THREAD

**Issue by klaasn** [go-swagger/go-swagger#212]
Hi, I have a model like this:

```
  Process:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
    required:
      - title
```

This generates a validate function like this:

```
 func (m *Process) validateTitle(formats strfmt.Registry) error {
	fmt.Printf("__%s__", m.Title)
	if err := validate.Required("title", "body", string(m.Title)); err != nil {
		return err
	}
	return nil
}
```

The problem is that this validates every empty string, so if the title field is not present, the object validates without errors. reflect.deepEqual does not give equality on empty strings.

Changing to validate.RequiredString solves the issue but I am not entirely sure on how to achieve that. The easy fix is to change validate.Required but that seems unclean.
