### ISSUE TITLE
Is it possible to generate model with `time.Time` type instead of `go-openapi/strfmt.Date`

### ISSUE THREAD

**Issue by Starnop** [go-swagger/go-swagger#2121]
## Problem statement

Please remove the sections that don't apply

## Swagger specification

Now I want to define a field with `time.Time` type, I have to define the spec as follows:

```
finishedTime:
  type: string
  format: "date-time"
  x-go-custom-tag: gorm:"type:varchar(255)"
```

After I use `swagger generate model` to generate the models form the spec, the generated result is as follows

```
// finished time
// Format: date-time
FinishedTime strfmt.DateTime `json:"finishedTime,omitempty" gorm:"type:varchar(255)"`
```

And the default marshal format of `strfmt.DateTime` is `RFC3339Millis = "2006-01-02T15:04:05.000Z07:00"` which is **not expected and not configurable**.

So I want to find a way to define the field with go type `time.Time`. Is there any way to do that? 

FYI
```
# swagger version
version: v0.19.0
commit: 312366608bbf17dd219190b66ab63bdc8b4d0db0
```
## Environment
swagger version: v0.19.0
go version: go1.12.9
OS:   Linux x86_64

**Comment by fredbi** [comment]
@Starnop type `strfmt.Time` has a configurable marshal format: `strfmt.MarshalFormat`, which defaults to `RFC339Millis` but you can change this at the package level.

**Comment by Starnop** [comment]
> but you can change this at the package level.

@fredbi Thanks for your reply. 

And sorry for not understanding this sentence well.  You mean updates the source code and rebuild it?  

In addition, I find an interesting extension `x-go-type`. However,  I have not found a good example. 

I define the swagger spec file as follows:
```
Demo:
  type: "object"
  properties:
    created_at:
      x-go-type:
        import:
          package: "time"
        type: "Time"
```

After exec the `swagger generate model` and the generated result is 

```
type Demo struct {

	// created at
	CreatedAt interface{} `json:"created_at,omitempty"`
}
```

And I expect the type is `time.Time`.
