### ISSUE TITLE
Failed to split definitions to multi files

### ISSUE THREAD

**Issue by mail2fish** [go-swagger/go-swagger#2124]
## Problem statement

A swagger file like this:

```yaml
consumes:
- application/json
definitions: 
  $ref: ./swagger_ymls/request_definitions.yml
  $ref: ./swagger_ymls/response_definitions.yml
```
always got:

json: cannot unmarshal string into Go struct field SwaggerProps.definitions of type struct { spec.SchemaProps; spec.SwaggerSchemaProps }

## Swagger specification

definitions

## Steps to reproduce

swagger validate

## Environment
version: v0.21.0
commit: 7c0fc3ee340f9d99d85573bc54a57e303a639692
go version: go1.13.4 darwin/amd64
OS:   macOS Catalina version 10.15.1 19B88
