### ISSUE TITLE
spec generating schema and type

### ISSUE THREAD

**Issue by nat2k5us** [go-swagger/go-swagger#2133]
// GetInfo returns combined balances
//
// swagger:route GET /something/accounts/{accounts}/info Something GetInfo
// Fetches the account info  for one or more given accounts
// Parameters:
// + name:        accounts
//   description: List of accounts in comma separated format.
//   in:          path
//   required:    true
//   type: string
// Responses:
//   200: Balances
//   400: ErrorResponse
//   401: ErrorResponse
//   404: ErrorResponse

This generates 
```
  parameters:
      - description: List of accounts in comma separated format.
        in: path
        name: accounts
        required: true
        schema:
          description: List of accounts in comma separated format.
          type: string
        type: string
```
the type for accounts is being generated twice. once in the schema: 
and another same level as schema - anyway to fix?
```
schema:
          description: List of accounts in comma separated format.
         type: string
       type: string
```
the schema section is failing the validation and manually being removed.
