### ISSUE TITLE
How to generate a model with  JSON ',string' directive for an int64 properties?

### ISSUE THREAD

**Issue by mail2fish** [go-swagger/go-swagger#2144]
## Problem statement
For generated strcut, How could to have ',string' directive in the JSON tag?

like below:

type CreateKnodeParams struct {

	// root id
	// Required: true
	RootID *int64 `json:"root_id,string"`
}

## Swagger specification

```
definitions:
  create_knode_params:
    type: object
    properties:
      root_id:
        type: integer
        format: int64
````

## Environment
version: v0.21.0
commit: 7c0fc3ee340f9d99d85573bc54a57e303a63969
OS:    macos

**Comment by mail2fish** [comment]
After checked code, It seems no option for the directive ',string' of the golang JSON tag .

So I just hack some code to do that.

**Comment by fredbi** [comment]
@mail2fish custom tags work as shown below, to _add_ new tags.
There is currently a way to specify the "omitempty" option in the json tag, but not the "string" option.

If you look at how the tuning "x-omitempty" extension is handled, you might be able to add support for some "x-json-string" option.

My personal take on this is that this would add yet more subtle behaviour in your unmarshalling, and you'd probably better off specifying a custom type that unmarshals strings and provide extra validation to validate numbers from strings.

Example using currently available tag options:
```yaml
definitions:
  create_knode_params:
    type: object
    properties:
      root_id:
        type: integer
        format: int64
        x-omitempty: true
        x-go-custom-tag: "string"
```

Yields:
```go
type CreateKnodeParams struct {

	// root id
	RootID int64 `json:"root_id" string`
}
```
