### ISSUE TITLE
x-order not working in generate spec

### ISSUE THREAD

**Issue by aasikraja** [go-swagger/go-swagger#2202]
x-order values annotated in schema but still order not changed in generated YAML

For eg:
In .go code:
type User struct  {
	// User name 
        // Extensions:
        //   x-order: 0
        Username string `json:"username"`
	// Password 
        // Extensions:
        //   x-order: 1
        Password string `json:"password"`
}
// userInfo request payload
// swagger:response userInfo
type swaggUserInfo struct {
        // in:body
        Body User
}
Generated YAML:
userInfo:
    properties:
      password:
        type: string
        x-go-name: Password
        x-order: 1
      username:
        type: string
        x-go-name: Username
        x-order: 0

Here “username” should come as the first key and “password” should be the second key. 
Kindly let me know how to annotate x-order in this case.

## Swagger specification
2.0

## Environment
swagger version: v0.12.0
go version: 1.12.12
OS: RHEL

**Comment by nanoninja** [comment]
hi,

I don't know if I'm using the extension well and I can't find many examples on Extensions but it doesn't work.

Struct

```go
type Product struct {
	// the id for this product
	//
	// Extensions:
	// ---
	// x-order: 1
	// ---
	//
	// swagger:strfmt uuid
	// type: string
	// required: true
	// example: 9d843ebb-f091-48c2-8a3d-5fcd03b8ff6f
	ID string `json:"id,omitempty"`

	// the name for this product
	//
	// required: true
	// min length: 3
	// max length: 255
	// example: product name
	Name string `json:"name" validate:"required,min=3,max=255"`

	// the description for this product
	//
	// required: true
	// min length: 5
	// max length: 500
	// example: description of product
	Description string `json:"description" validate:"required,min=5,max=500"`

	// the flag of activation for this product
	//
	// required: false
	// type: boolean
	Active bool `json:"active"`

	// the price for this product
	//
	// required: true
	// type: double
	// example: 29.99
	Price float64 `json:"price" validate:"required"`

	// the created date for this product
	//
	// required: false
	// example: 0001-01-01T00:00:00Z
	// swagger:strfmt date-time
	DateCreated time.Time `json:"date_created,omitempty"`

	// the updated date for this product
	//
	// required: false
	// example: 0001-01-01T00:00:00Z
	// swagger:strfmt date-time
	DateUpdated time.Time `json:"date_updated,omitempty"`
}
```

Command


```sh
swagger generate spec -m -o ./swagger.yaml
```

Yaml

```yaml
product:
    description: Product model
    properties:
      active:
        description: the flag of activation for this product
        type: boolean
        x-go-name: Active
      date_created:
        description: the created date for this product
        example: "0001-01-01T00:00:00Z"
        format: date-time
        type: string
        x-go-name: DateCreated
      date_updated:
        description: the updated date for this product
        example: "0001-01-01T00:00:00Z"
        format: date-time
        type: string
        x-go-name: DateUpdated
      description:
        description: the description for this product
        example: description of product
        maxLength: 500
        minLength: 5
        type: string
        x-go-name: Description
      id:
        description: the id for this product
        format: uuid
        type: string
        x-go-name: ID
        x-order: 1
      name:
        description: the name for this product
        example: product name
        maxLength: 255
        minLength: 3
        type: string
        x-go-name: Name
      price:
        description: the price for this product
        example: 29.99
        format: double
        type: number
        x-go-name: Price
    required:
    - name
    - description
    - price
    type: object
    x-go-name: Product
    x-go-package: github.com/nanoninja/fakeapi/internal/product
``` 

When I start the server it's always listed in alphabetical order.

```sh
swagger serve --port 8000 -F=swagger swagger.yaml
```

Result in Swagger UI

```json
  {
    "active": true,
    "date_created": "0001-01-01T00:00:00Z",
    "date_updated": "0001-01-01T00:00:00Z",
    "description": "description of product",
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "name": "product name",
    "price": 29.99
  }
```

Maybe I'm doing it wrong, if you had an example I'm interested. Thanks for your help.

**Comment by nxvinh222** [comment]
+1 on this

**Comment by helloshaohua** [comment]
Why do you need to sort the model fields? Since the default sorting is used, why does x-order not take effect, and this problem still exists?

**Comment by casualjim** [comment]
x-order is currently only used in the code generation path, to get deterministic ordering of properties in go. It's not used in the spec. our serialization uses go maps and they are randomized

**Comment by peanutgyz** [comment]
> 

Do we have plan to support this ? To keep go struct filed order in generated spec?

**Comment by ChandanChainani** [comment]
@aasikraja to get the order in generated schema you need to wrap `x-order` value `number` in double quotes (`"`) or single quotes (`'`).

```
type User struct {
  // User name
  // Extensions:
  // x-order: "0"
  Username string json:"username"
  // Password
  // Extensions:
  // x-order: "1"
  Password string json:"password"
}

// userInfo request payload
// swagger:response userInfo
type swaggUserInfo struct {
  // in:body
  Body User
}
```

Generated YAML:
```
userInfo:
  properties:
    username:
      type: string
      x-go-name: Username
      x-order: 0
    password:
      type: string
      x-go-name: Password
      x-order: 1
```
cc: @krashish8 @nxvinh222 @helloshaohua @casualjim @peanutgyz

The problem seems to be in [`go-openapi/spec`](https://github.com/go-openapi/spec) I am currently debugging the issue and will raise a fix.
