### ISSUE TITLE
Api-key headers order handling

### ISSUE THREAD

**Issue by ajramos** [go-swagger/go-swagger#2217]
## Problem statement
I have two apiKey entries in security definition that applies to the same method.
One of them, 'apikey'  for invoking the api methods, and the other one 'accessToken' brings a token with the user authentication token. It is a legacy code and the login mechanism was implemented in that way.

The handler of the 'apiKey' header only checks whether the apiKey is in the api-keys list and return nil for principal model (see code simplification below):
```
api.IsAPITrustedAuth = func(token string) (*models.Principal, error) {
        err := authtoken.CheckAuthKey(&token)
	if err != nil {
		err = fmt.Errorf(constant.WrongAPIKeyMessage)
	}
	return nil, err
}
```
and the 'accessToken' handler checks the validity of the accesstoken, and return the user details if everything goes fine (see code simplification below):
```
	api.IsUserAuth = func(token string) (*models.Principal, error) {

		user, err := cache.RetrieveUserData(&token)

		if err != nil {
			err = fmt.Errorf(constant.UserTokenProblemMessage)
			return nil, err
		}
		p := models.Principal{
			ID:           user.ID,
		}
		return &p, nil
	}
```
finally when handling the request at the target method (see simplified code below), I was assuming the 'apikey' handler was executed before 'accessToken' handler and expecting model.Principal to be populated with user details and indeed it usually happens in that way (90% of times) but there are sometimes the program executes the 'apikey' handler last and pass a nil value to the method, hence raising an controlled error. then my question is whether there is any way that i can force the order of api-key authentication headers. 
Thanks a lot in advance for your help. 
```
api.MethodHandler = operations.MethodHandlerFunc(func(params operations.MethodParams, principal *models.Principal) middleware.Responder {
		if principal == nil {
			return operations.NewMethodDefault(http.StatusUnauthorized).WithPayload(
				apicommon.CreateError(
					constant.UserDataMissingCode,
					constant.UserDataMissingMessage))
		} else {
```

## Swagger specification
```
securityDefinitions:
/--omited--content--/
    isAPITrusted:
        type: apiKey
        in: header
        name: apikey
    isUser:
        type: apiKey
        in: header
        name: accessToken
/--omited--content--/
      security:
        - isAPITrusted: []
          isUser: []
/--omited--content--/
```
I am generating the server code with the following command:
```
swagger generate server -A server-api -P models.Principal -f ./swagger/server/server.yaml
```
## Environment
swagger version: v0.21.0  
go version: 1.13.4  
OS:   macOS Mojave 10.14.6
