### ISSUE TITLE
importing struct with x-go-type generates client code which doesnt compile

### ISSUE THREAD

**Issue by eitanb** [go-swagger/go-swagger#2224]
## Problem statement
i'm trying to extract a model from our swagger document & consume it from an external source. we want the the type to be generated by DB access layer which also has a schema & generates code.

when doing so i've hit 2 issues:
1. The API's which use the imported types changed so that they take a value rather than a pointer. this implies most of the called API's which forces a huge change to the code base.
Notet hat the type definition has changed a bit - its the exact same definition when comparing the generated go code using diff tool.
That's the simple one :)

2. some API's which take a type T imported using the x-go-type now generate invalid code for the client.
these API's consume the imported type within the API body. they generate the type as value rather than pointer but still check for it to be nil, which fails to compile.
so having a workaround to make the value back into a pointer would be a work-around.
 

## Swagger specification
the part which imports the type looks like so:
```
Hotspot:
  x-go-type:
    import:
      package: fbc/xwf/swagger/gen/ents
    type: Hotspot
  x-nullable: true
```

The API declaration (schema version 2.0) is:
```
post:
  tags:
  - hotspot
  summary: Create a Hotspot
  operationId: "CreateHotspot"
  consumes:
  - application/json
  produces:
  - application/json
  parameters:
  - in: body
    name: Hotspot
    required: false
    schema:
      $ref: '#/definitions/Hotspot'
  responses:
    201:
      description: Hotspot created.
      schema:
        $ref: '#/definitions/Hotspot'
    400:
      description: Bad request.
      schema:
        $ref: '#/definitions/Error'
    422:
      description: Unprocessable entity
      schema:
        $ref: '#/definitions/Error'
    500:
      description: Unexpected error.
      schema:
        $ref: '#/definitions/Error'
```

## Steps to reproduce
generating client code generates the following invalid code:

```
func (o *CreateHotspotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

        if err := r.SetTimeout(o.timeout); err != nil {
                return err
        }
        var res []error

        if o.Hotspot != nil {                   <<<<<<<<<<<<<<< This fails to compile. o.Hotspot is a value, NOT a pointer
                if err := r.SetBodyParam(o.Hotspot); err != nil {
                        return err
                }
        }

        if len(res) > 0 {
                return errors.CompositeValidationError(res...)
        }
        return nil
}
```

## Environment
swagger version: v0.21.0
commit: 7c0fc3ee340f9d99d85573bc54a57e303a639692  
go version: go1.13.5 darwin/amd64
OS:   MacOS Mojave, 10.14.6

**Comment by fredbi** [comment]
Do you have the specification which leads to the generation of `HotSpot`, or the code defining this type?

**Comment by eitanb** [comment]
for the first phase, i've just moved these out of a swagger.yaml document into another, generate the go code & consume it
in later phase, we plan to start consuming these types from another tool, so we'll replace them one-by-one
that's why i consume them as x-go-type rather than using $ref or other methods.

The hotspot is as follows:

definitions:
  Time:
    x-go-type:
      import:
        package: time
      type: Time

  Base:
    properties: &base
      id:
        type: integer
        format: uint64
        x-go-custom-tag: gorm:"primary_key"
      FBID:
        type: integer
        format: uint64
        x-go-custom-tag: gorm:"index"
      created_at:
        $ref: "#/definitions/Time"
      updated_at:
        $ref: "#/definitions/Time"
      version:
        type: integer
        format: uint64

  Hotspot:
    type: object
    allOf:
      - properties: *base
      - properties:
          access_points:
            type: array
            items:
              $ref: '#/definitions/AccessPoint'
          type:
            $ref: '#/definitions/HotspotType'
        required:
          - type

  AccessPoint:
    type: object
    allOf:
      - properties: *base
      - properties:
          mac_address:
            type: string
            x-go-custom-tag: gorm:"index;not null;unique"
          hotspot_id:
            type: integer
            format: uint64
          hotspot:
            $ref: '#/definitions/Hotspot'

**Comment by eitanb** [comment]
p.s.

i've seen https://github.com/go-swagger/go-swagger/issues/2081 but its not relevant bcz my object isnt empty - it has lots of members

**Comment by eitanb** [comment]
Hi,

Its been some time since this issue is open & we've since been fixing the auto-generated code a few times manually.
Is there any plan/estimate on when will this issue be addressed ?

Thanks
Eitan

**Comment by fredbi** [comment]
@eitanb The problem with the client generation (and the pointer problem) lies with the shortcut definition you use:
```
Hotspot:
  x-go-type:
    import:
      package: fbc/xwf/swagger/gen/ents
    type: Hotspot
  x-nullable: true
```

Since you do no give any information about the type, save an external reference _that is not resolved at codegen time_,
the codegen interprets the type as equivalent to:
```
HotSpot:
  x-nullable: true
```
which means a lot: in particular, this is rendered as a map, so it doesn't need a pointer.
but at build time, the reference is resolved, and surprise, the actual type is different.

In order to make this work, you need to provide some minimal information about the time. Could be a $ref to the type,
but doesn't need to be so detailed, since only the essential characteristics of the object need to be capture (is this an array, an object,  a primitive type, a map, is it nullable).

In your example, I managed to have both server and client building fine with the following (slightly modified) definition:
```
  Hotspot:
    type: object
    properties:
      fake:  # <- this tells the codegen that this is a real object. The property mentioned here is not used.
        type: integer
    x-go-type:
      type: Hotspot
      import:
        package: github.com/go-swagger/go-swagger/fixtures/bugs/2224/models/external
    #x-nullable: true # <- works with or without this extra nullable. Just depends on what you really want
```

**Comment by fredbi** [comment]
There is unfortunately not much we can do about that kind of issue, which is idiosyncratic to the method of injecting unknown types.
However, I believe we could improve usability by supporting some "hints" in the `x-go-type` tag.  For example:
```yaml
Hotspot:
  x-go-type:
    import:
      package: fbc/xwf/swagger/gen/ents
    type: Hotspot
    kind: object # <- object|map|array|primitive|baseType
```
