### ISSUE TITLE
how to write swagger:response schema that produces application/xml

### ISSUE THREAD

**Issue by aasikraja** [go-swagger/go-swagger#2245]
I am trying to figure out how to write and annotate a go-swagger response struct that produces the following swagger output:

<?xml version="1.0" encoding="UTF-8"?>
<Users ID="string" Label="string" >
	<Properties Path="string" SearchType="string">
		<value>string</value>
		<type>string</type>
	</properties>
</Users>

I have defined like below but go-swagger generating this as a json struct only:
type Users struct {
        ID string `xml:"id,attr"`
        Label string `xml:"label,attr"`
}

Could some body help me how to create swagger:response in this case.

## Environment
swagger version: v0.21.0
go version: go1.12.12  
OS:   RHEL

**Comment by aasikraja** [comment]
Kindly somebody reply me for this query

**Comment by casualjim** [comment]
I don't think we have support for XML in the code scanner. You're the first one in 5 years who's asked for it.
Assuming your case is for scanning code and generating a swagger spec.

**Comment by aasikraja** [comment]
Thank you for the reply @casualjim yes i am generating the spec document by annotating on the code.

**Comment by movergan** [comment]
We actually encountered into the same issue. The modes generated via swagger client are json only:
Example from the default Petstore, for instance:

```
  /pet/{petId}:
    get:
      tags:
      - "pet"
      summary: "Find pet by ID"
      description: "Returns a single pet"
      operationId: "getPetById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "petId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
```
Pay attention:
      - "application/xml"
      - "application/json"

And the model is:
```
package swagger

type Pet struct {
	Id int64 `json:"id,omitempty"`
	Category *Category `json:"category,omitempty"`
	Name string `json:"name"`
	PhotoUrls []string `json:"photoUrls"`
	Tags []Tag `json:"tags,omitempty"`
	// pet status in the store
	Status string `json:"status,omitempty"`
}
```
So what happen when you actually get an XML response is, the client cannot map it into the model and although the server returned 200, you'll end up having an empty structure.
