### ISSUE TITLE
"Namespaces" for definitions

### ISSUE THREAD

**Issue by pawelpeksa** [go-swagger/go-swagger#2268]
## Problem statement

Is it possible to divide definitions in let's call them into "namespaces"? I would like to have two separate definition blocks in one swagger file and refer to them for different endpoints. 

```
 definitions:
  SomeDefinitions:
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

  PetDefinitions:
    HeHeObject:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
```

Having something like this I'd like to refer to definitions in a following way:
`$ref: '#/definitions/PetDefinitions/HeHeObject'` 
and 
`$ref: '#/definitions/ErrorResponse/PetData'`

It seems to me that here: https://swagger.io/docs/specification/components/ it's described how to use components. I tried different variations of the examples from this website and of the code that I put above of course. In all cases I was getting following errors when validating/generating:

```
- definitions.SomeDefinitions.ErrorResponse in body is a forbidden property
- definitions.PetDefinitions.HeHeObject in body is a forbidden property
```
 is there any way around it? Or it's not feasible?

## Environment
swagger version: v0.19.0 
go version: 1.12.7
OS: macOS Catalina
