### ISSUE TITLE
Object from imported package missing Validate() method

### ISSUE THREAD

**Issue by YanzhaoLi** [go-swagger/go-swagger#2285]
## Problem statement

In the swagger specification, I used an object from the 3rd party package.
```
ThirdPartyObject:
    type: object
    x-go-type:
         import:
             package: "ThirdPartyPackage/v1"
         type: "ThirdPartyObject"
```

This object is used in a post request.  The generated swagger code assumes the object has an Validate() method, however the `ThirdPartyObject` has no Validate() method.

```
if runtime.HasBody(r) {
		defer r.Body.Close()
		var body v1.ThirdPartyObject
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}
```

Any workaround for this issue?
