### ISSUE TITLE
Unable to generate Swagger spec with more than one security header using "AND" logic.

### ISSUE THREAD

**Issue by utkarsh-var** [go-swagger/go-swagger#2294]
## Problem statement
I'm unable to generate the Swagger specification for making more than one security header required for authentication. For example, I'm using `x_client_id` and `access_token` for authenticating the request, but I'm not able to generate the Swagger specs for it.

The issues [here](https://github.com/go-swagger/go-swagger/issues/1089) mentions that the go swagger has the support for **AND** logic in the Security headers, but I'm not able to find the documentation for the same.

I'm using the following comments for generating the Swagger specs:-
```
//  security:
//   - x_client_id:
//      access_token:
//
//  SecurityDefinitions:
//  x_client_id:
//    type: apiKey
//    name: x_client_id
//    in: header
//  access_token:
//    type: apiKey
//    name: Authorization
//    in: header
```

It generates the following Swagger specs:-
```
security:
- x_client_id: []
- access_token: []
securityDefinitions:
  access_token:
    in: header
    name: Authorization
    type: apiKey
  x_client_id:
    in: header
    name: x_client_id
    type: apiKey
```

The expected output should be:- 
```
security:
- x_client_id: []
  access_token: []
securityDefinitions:
  access_token:
    in: header
    name: Authorization
    type: apiKey
  x_client_id:
    description: Use the client id provided by the API
    in: header
    name: x_client_id
    type: apiKey
```

## Environment
swagger version: 2.0
go version: go1.14.2
OS: macOS 10.14.5
