### ISSUE TITLE
What is the intended use of RegisterFormat?

### ISSUE THREAD

**Issue by vincentvanderweele** [go-swagger/go-swagger#2321]
I would like to add a domain-specific custom format to my swagger spec and generate corresponding code. Based on the existing `RegisterFormat` method on the generated api, I would expect I can do this:

```go
api := operations.NewMyAPI(spec)
api.RegisterFormat("custom", customFormatter, customValidator)
```

and use it in my spec like this:

```yaml
definitions:
  CustomObject:
    type: object
    properties:
      customField:
        type: string
        format: custom
```

but this doesn't work because the allowed list of formats used in the generator is hardcoded. So my custom format will never make it to the generated model.

---

Does that mean that `RegisterFormat` is only useful for types that I provide using `x-go-type`? I found issue #732 hinting that providing custom formats has not been fully implemented. Is that the case or am I missing something?
