### ISSUE TITLE
how to add property `in:formData` for struct's all field

### ISSUE THREAD

**Issue by darcyaf** [go-swagger/go-swagger#2323]
Is there someway to add property `in:formData` for  UsersModify's all fields?
It seems I need add one by one.
```
// swagger:parameters put-users
type UsersModify struct {
	// in: formData
	params.UsersModify
}

type UsersModify struct {
	Nickname   string            `json:"nickname" validate:"omitempty,max=32,min=2"`
	Avatar     string            `json:"avatar" validate:"omitempty,url"`
}
```
I wanna generate file like this:

```
      parameters:
      - in: form
        name: nickname
        type: string
        x-go-name: Nickname
      - in: form
        name: avatar
        type: string
        x-go-name: Avatar
```
