### ISSUE TITLE
file parameter with maxLength: not enough arguments in call to "github.com/go-openapi/errors".ExceedsMaximum

### ISSUE THREAD

**Issue by dmitryermichev** [go-swagger/go-swagger#2342]
## Problem statement
I set up file parameter with maxLength option in specs. 
```yaml 

```yaml
  parameters:
        - name: "file"
          in: "formData"
          description: "file to upload"
          required: false
          type: "file"
          maxLength: 5242880 #5mb
```

After that validation added in parameters struct 
```go
func (o *AdminCourseUploadPhotoParams) bindFile(file multipart.File, header *multipart.FileHeader) error {
	size, _ := file.Seek(0, io.SeekEnd)
	file.Seek(0, io.SeekStart)
	if size > 5242880 {
		return errors.ExceedsMaximum("file", "formData", 5242880, false)
	}
	return nil
}
```
And it compiles with error
```go
../../restapi/operations/course/admin_course_upload_photo_parameters.go:94:31: not enough arguments in call to "github.com/go-openapi/errors".ExceedsMaximum
	have (string, string, number, bool)
	want (string, string, float64, bool, interface {})
```

## Swagger specification

```yaml
  parameters:
        - in: path
          name: id
          required: true
          type: integer
        - name: "file"
          in: "formData"
          description: "file to upload"
          required: false
          type: "file"
          maxLength: 5242880 #5mb
```

## Steps to reproduce

Add file parameter with maxLength property

## Environment
swagger version: v0.24.0 
go version: go1.13.8 linux/amd64
OS: Ubuntu 18.04.3 LTS
