### ISSUE TITLE
Upload of large files fails due to 32 mb limit

### ISSUE THREAD

**Issue by tsorya** [go-swagger/go-swagger#2370]
## Problem statement
Failing to upload file more than 32mb
Please remove the sections that don't apply

## Swagger specification
```
post:
      tags:
        - ...
      summary: Agent API to upload logs.
      operationId: UploadFile
      consumes:
        - multipart/form-data
      parameters:
        - in: path
          name: id
          type: string
          format: uuid
          required: true
        - in: formData
          name: upfile
          type: file
          required: false
          description: The file to upload.
```

## Steps to reproduce
auto generated curl with file of size bigger than 32mb

## Environment
swagger version: 2.0
go version: go1.14.3
OS:  Centos

`if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}
`
fails with 400.
There is a way to upload large file without changing this part?

Thanks a lot.
