### ISSUE TITLE
Embedded uuid field interpreted as bytearray

### ISSUE THREAD

**Issue by unullmass** [go-swagger/go-swagger#2404]
## Problem statement

For generating spec from source we have a bunch of definition fields that have been implemented as byte-arrays in source code. These show up as integer (uint8) arrays in the spec. This causes inconsistent behavior when the specs are run through a client like Postman or ReadyAPI. Is there any way to force go-swagger to convert these fields into strings using a combination of swagger annotations?

## Swagger specification

Source struct:

```go
type CaCertificate struct {
	Name        string `json:"name,omitempty"`
	Type        string `json:"type,omitempty"`
	Certificate []byte `json:"certificate,omitempty"`
}
```

results in this spec:

```yaml
  CaCertificate:
    description: CaCertificate is to represent certificate/ca certificate
    properties:
      certificate:
        items:
          format: uint8
          type: integer
        type: array
        x-go-name: Certificate
      name:
        type: string
        x-go-name: Name
      type:
        type: string
        x-go-name: Type
    type: object
    x-go-package: github.com/intel-secl/intel-secl/v3/pkg/model/hvs
```

Another example:

```go
type HostFlavorgroup struct {
	HostId        uuid.UUID `json:"host_id,omitempty"`
	FlavorgroupId uuid.UUID `json:"flavorgroup_id,omitempty"`
}

```
generates this spec:

```yaml
    HostFlavorgroup:
      properties:
        flavorgroup_id:
          $ref: "#/components/schemas/UUID"
        host_id:
          $ref: "#/components/schemas/UUID"
      type: object
      x-go-package: github.com/intel-secl/intel-secl/v3/pkg/model/hvs

definitions:
  UUID:
    description: |-
      A UUID is a 128 bit (16 byte) Universal Unique IDentifier as defined in RFC
      4122.
    items:
      format: uint8
      type: integer
    type: array
    x-go-package: github.com/google/uuid

```
## Steps to reproduce

	swagger generate spec -o hvs-openapi.yml --scan-models
	swagger validate hvs-openapi.yml

## Environment
swagger version: v0.24.0 | 094421c7a2e1a7982cb28fdc0fc2bda610bbcc56
go version: 1.13-1.14
OS:   RHEL 8.1
