### ISSUE TITLE
how add example to yml from golang code

### ISSUE THREAD

**Issue by utwtjm** [go-swagger/go-swagger#2407]
# golang

``` 

// success
// swagger:response encryptSuccessResponse
type encryptSuccessResponse struct {
    // example:[1, 2, 3] <------------------------------------------------------
    // in:body
    Body []string
}

```

# yml 

``` 

encryptSuccessResponse:
    description: success
    schema:
      items:
        type: string
      type: array 

```

> example not show in yml  

> my English isn't good. sorry
