### ISSUE TITLE
Go swagger can't validate all uint64 in path parameters

### ISSUE THREAD

**Issue by DejeroDaniel** [go-swagger/go-swagger#2448]
## Problem statement

The generated code for checking the minimum value of a path parameter consists of this:

```
	if err := validate.MinimumInt("serial", "path", int64(o.Serial), 1, false); err != nil {
		return err
	}
```
Which, as you can see, typecasts the integer to an int64. This results in failure if Serial is a large enough uint64.

## Swagger specification
```
      parameters:
        - in: path
          name: serial
          type: integer
          format: uint64
          required: true
          description: The serial number
          minimum: 1
```
## Steps to reproduce
Create a route with the given path parameter. Randomly generate a uint64 larger than the biggest int64. go swagger returns a 422 due to the above generated code.
## Environment
swagger version: v0.20.1
go version: 1.15.5
OS:   Ubuntu
