### ISSUE TITLE
Enumerated string types get generated constants, but enumerated integer types do not

### ISSUE THREAD

**Issue by mdelvecchio-wasabi** [go-swagger/go-swagger#2451]
## Problem statement

I am trying to define an enumerated integer type with well-named constants using the **x-go-const-names:** property.  I can't get the generated type to include any constants for integer enums.

## Swagger specification

```
  EventType:
    type: integer
    format: uint32
    description: Event Type
    enum:
      - 1
      - 2
      - 3

    x-go-const-names:
      - One
      - Two
      - Three
```

## Steps to reproduce

Generate models with the above definition.  The resulting type is as expected:

```
// EventType Event Type
//
// swagger:model eventType
type EventType uint32
```

But there are no Go constants defined for EventTypeOne, EventTypeTwo, or EventTypeThree.  In fact, there are no constants defined with any name at all.

If I change the type to string, and change the enum values to "1", "2", and "3", I do get constants defined, but without the x-go-const-names values I specified:

```
const (

	// EventTypeNr1 captures enum value "1"
	EventTypeNr1 EventType = "1"

	// EventTypeNr2 captures enum value "2"
	EventTypeNr2 EventType = "2"

	// EventTypeNr3 captures enum value "3"
	EventTypeNr3 EventType = "3"
)
```

For my integer enum, I would expect to see something like this:

```
const (

	// EventTypeOne captures enum value 1
	EventTypeOne EventType = 1

	// EventTypeTwo captures enum value 2
	EventTypeTwo EventType = 2

	// EventTypeThree captures enum value 3
	EventTypeThree EventType = 3
)
```

But instead, there are no constants defined at all.

How can I generate my desired constants for an integer enum?

Thanks.

## Environment
swagger version: v0.23.0
go version: 1.12.17
OS:   Ubuntu 18
