### ISSUE TITLE
add support for ULID to swagger:strfmt

### ISSUE THREAD

**Issue by elipavlov** [go-swagger/go-swagger#2467]
## Problem statement

It's great that we have feature like string format for the UUID strings which described here:
https://goswagger.io/use/spec/strfmt.html

Recently i've learnt about ULID identity provider: 
https://github.com/ulid/spec

My proposal is to add the same mechanic for the ULID format as for UUID.

## Swagger specification
Examples would be:

1) 
```yaml
---
definitions:
  user:
    properties:
      id:
        type: string
        format: ulid
```

2) 
```yaml
---
definitions:
  ULIDType:
    type: string
    format: ulid
  User:
    properties:
      id:
        $ref: '#/definitions/ULIDType'
```
