### ISSUE TITLE
x-go-custom-tag tag not taken into account in some cases since 0.26.0

### ISSUE THREAD

**Issue by maxatome** [go-swagger/go-swagger#2499]
## Problem statement

`x-go-custom-tag` tag is no longer taken into account for a property.

Following spec using swagger-v0.26.0 generates:
```
type Bad struct {

        // blah blah blah
        Test MyType `json:"test,omitempty"`
}
```

while swagger-v0.25.0 generates:
```
type Bad struct {
        
        // blah blah blah
        Test MyType `json:"test,omitempty" db:"test"`
}
```

## Swagger specification

```yaml
definitions:
  MyType:
    type: array
    items:
      type: string

  Bad:
    type: object
    properties:
      test:
        $ref:  '#/definitions/MyType' 
        description: blah blah blah
        x-go-custom-tag: db:"test"                                     

  Ok:
    type: object
    properties:
      test:
        type: array
        items:
          type: string
        description: balh blah blah
        x-go-custom-tag: db:"test"                                     
```
## Steps to reproduce

```
swagger-v0.26.0 generate model -f api.yaml
```

## Environment
swagger version: 0.26.0
go version: 1.15.7
OS:   Linux amd64

**Comment by fredbi** [comment]
```
 properties:
      test:
        $ref:  '#/definitions/MyType' 
        description: blah blah blah
        x-go-custom-tag: db:"test"                                     
```

This is because we are now stricter on the jsonschema spec that is "every sibling to a $ref" is ignored.
In this particular use case, I understand that this is a problem, though ...

**Comment by fredbi** [comment]
The only way we could solve this recurring use case is to add some "Annotations" field to `spec.Ref`, with extensions. At least this piece of information wouldn't be lost during unmarshaling/marshaling and the swagger codegen would have the opportunity to check for extensions in this block

**Comment by maxatome** [comment]
> This is because we are now stricter on the jsonschema spec that is "every sibling to a $ref" is ignored.

But `description` is not ignored here, that is why it is a bit weird...

**Comment by maxatome** [comment]
Setting:
```
  MyType:
    type: array
    items:
      type: string
    x-go-custom-tag: db:"test"
```
works, but admit it is not obvious... IMHO `MyType` should not carry the custom tag of a field using it.
