### ISSUE TITLE
Generating enums with "-" from spec

### ISSUE THREAD

**Issue by eugene-rockspoon** [go-swagger/go-swagger#2515]
## Problem statement

`Enum` values with the character `-` generated with literal `Dash` as `MyEnumLovelyDashValue MyEnum = "lovely-value"`

The main problem that before last update it skipped the `-` and generated proper names as `MyEnumLovelyValue MyEnum = "lovely-value"

## Swagger specification
swagger: '2.0'
## Steps to reproduce
 1) Create swagger.yaml with enum type:
```
  MyType:
    type: string
    enum:
      - one-two
      - two-three
      - ten-one
```
2) Run `swagger generate model --spec=swagger.yaml`
## Environment
swagger version: 0.26.1 
go version: go1.13.9 
OS:   darwin/amd64
