### ISSUE TITLE
How to force the generation of the swagger spec from code to turn []byte into string

### ISSUE THREAD

**Issue by tanis2000** [go-swagger/go-swagger#2519]
I have the following scenario:

- I need to create a swagger spec file from code
- My models are being generated from avro schemas through gogen-avro
- I would like fields that are []byte to be expressed in the swagger spec as string as that's what the Java swagger client generator expects for byte arrays

The model looks like this:

```
// swagger:model
type EventsActorTaskEvent struct {
		Metadata *EventsMetadataDescriptor
		NotificationDataBinary []byte
}
```

What I'm getting at the moment is the following:

```
      NotificationDataBinary:
        items:
          format: uint8
          type: integer
        type: array
```

but the correct notation should be:

```
      NotificationDataBinary:
        type: string
        format: byte
```

I saw this issue that is similar: https://github.com/go-swagger/go-swagger/issues/2404

But I cannot change the type of the field as it's being generated and I have no control over that. 
Is there any other way to hint go-swagger about what the field should be translated to?
