### ISSUE TITLE
go-swagger documentation is not updated for swagger enum 

### ISSUE THREAD

**Issue by pradeepp28** [go-swagger/go-swagger#2528]
## Problem statement
https://goswagger.io/use/spec.html doesn't explain `swagger:enum` usage

**Comment by dy21335** [comment]
do you know how to use `swagger:enum`?

**Comment by pradeepp28** [comment]
Yes, 

https://github.com/go-swagger/go-swagger/pull/744
https://github.com/go-swagger/go-swagger/pull/2176

These two links helped.

**Comment by herlon214** [comment]
Yeah, but I'm wondering if is there a way to generate enums with `int64` doing `iota`.

My spec:
```yaml
type: integer
description: >
   * `0` - Failed
   * `1` - In progress
   * `2` - Success
enum:
  - 0
  - 1
  - 2
```

Produces this:
```go
// Status * `0` - Failed * `1` - In progress * `2` - Success
//
//
// swagger:model Status
type Status int64

// for schema
var statusEnum []interface{}
```

Is there a way to get the the result with `iota`?
Something like:
```go
# ...
type Status int64
const (
	StatusAvailable Status = iota
	StatusPending  Status
	StatusSold     Status
)
#...
```
