### ISSUE TITLE
strfmt.bsonobjectid validation fails

### ISSUE THREAD

**Issue by dimovnike** [go-swagger/go-swagger#2616]
Fields using bsonobjectid format in parameters or models fail to validate. For example this spec:

```yaml
parameters: 
        - name: id
          in: path
          required: true
          type: string
          format: bsonobjectid
```

Generates the following validation code:

```go
func (m *ReportBase) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	if err := validate.FormatOf("id", "body", "bsonobjectid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}
```
However, this part `m.ID.String()` returns a value that can not be validated by the FormatOf(). The returned value is in the format `ObjectID("hex string")` but validator expects just the hex string.

The error from swagger is:
```json
{
    "code": 601,
    "message": "id in path must be of type bsonobjectid: \"ObjectID(\\\"60a7903427a1e6666d2b998c\\\")\""
}
```
