### ISSUE TITLE
generate cli not generating flags for array params in path

### ISSUE THREAD

**Issue by dimovnike** [go-swagger/go-swagger#2617]
The following spec generates no flags for the operation in cli:

```yaml
/delete/{report_ids}:
    post:
      parameters:
      - type: array
        items:
          type: string
        name: report_ids
        in: path
        required: true
```

The generated flags show as:

```
Deletes reports.

Usage:
  main operations delete_reports [flags]

Flags:
  -h, --help   help for delete_reports

Global Flags:
      --authorization string   
      --config string          config file path
      --debug                  output debug logs
      --dry-run                do not send the request to server
      --hostname string        hostname of the service (default "localhost")
      --scheme string          Choose from: [http https] (default "http")
```

All other operations have proper flags generated.

I am using swager from latest master v0.26.0-63-gff73c22b
