### ISSUE TITLE
Is it possible to use $ref with x-go-type

### ISSUE THREAD

**Issue by michaelkub** [go-swagger/go-swagger#2643]
We have two swaggers, one for data model and second for api implementation, now we are pointing objects from model in the following way:
```
Some:
    type: object
    properties:
      fake: # <- this tells the codegen that this is a real object. The property mentioned here is not used.
        type: integer
    x-go-type:
      import:
        package: some/some/swagger/gen/some
      type: Some
    x-nullable: true
```

Problem is when we are trying to generate JS client based on this swagger, js swagger not familiar with x-go-type tags, but when we are switching to $ref tags, server/client implementation will generate all data model object under new package
Example of change:
```
Some:
   $ref: `../swagger/swagger.yaml#/Some`
```

Is there way to use $ref with x-go-type:, or mark generated models as belongs to correct golang package

## Environment
swagger version: 0.25 
go version: 1.16
OS:   Mac
