### ISSUE TITLE
Specify the same parameter more than one time

### ISSUE THREAD

**Issue by ThreadedStream** [go-swagger/go-swagger#2786]
I'm currently trying to make the request of the following sort 
```
    https://<netbox_host>/dcim/devices/?q=&role_id=16&role_id=97
```
You clearly see two occurrences of role_id param with different values assigned to each of them. 
How do I model the same request, but in the context of client library generated by swagger?

**Comment by casualjim** [comment]
You would specify a collection format of "multi". Look for collectionFormat on this page: https://swagger.io/specification/v2/

**Comment by ThreadedStream** [comment]
@casualjim thanks for help. I specified collectionFormat to be of multi type, but now I wonder how would I specify it in client code, since nothing seems to have changed. I tried to write ```roleID  = "16&97"```, but it didn't work.

**Comment by casualjim** [comment]
roleid should be generated as an array. it should be specified as a query parameter with:

```yaml
type: array
items: string
collectionFormat: multi
```

here's an example from the petstore spec:

```yaml
 get:
      tags:
        - pet
      summary: List pets
      operationId: PetList
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          type: array
          items:
            type: string
            enum:
              - available
              - pending
              - sold
            default: available
          collectionFormat: multi
```
