### ISSUE TITLE
go-swagger silently stops parsing `swagger:allOf` when `GOROOT` is not set

### ISSUE THREAD

**Issue by colearendt** [go-swagger/go-swagger#2874]
## Problem statement

I am generating the swagger spec from code, and recognized that different terminals were giving me different output with no logs / messages. Ideally things would "just work." If something has failed / cannot be determined / cannot be followed / `GOROOT` is required, then a warning should be emitted.

## Steps to reproduce

Build a nested object structure inside of a `swagger:response`. For instance:

```
type inner struct {
	Hello string
}

// swagger:response
type test struct {
	// swagger:allOf
	Inner inner
}
```

If you generate in a naked shell:
```
# swagger generate spec -o ./swagger.json -w . -m
    "test": {
      "description": "",
      "headers": {
        "Inner": {}
      }
    }
```

Versus with `GOROOT` defined:
```
# GOROOT=/usr/lib/go-1.18 swagger generate spec -o ./swagger.json -w . -m
    "inner": {
      "type": "object",
      "properties": {
        "Hello": {
          "type": "string"
        }
      },
      "x-go-package": "handler/function"
    }
...
    "test": {
      "description": "",
      "schema": {
        "$ref": "#/definitions/inner"
      },
      "headers": {
        "Inner": {}
      }
    }
```

## Environment
swagger version: 
```
version: v0.30.3
commit: ecf6f05b6ecc1b1725c8569534f133fa27e9de6b
```
go version: go version go1.18.1 linux/amd64
OS:  WSL2 (Ubuntu 22.04)

**Comment by colearendt** [comment]
Worth noting that it does not seem to be just `allOf` that is affected here. General path traversal seems to be silently broken

**Comment by Isnor** [comment]
I had the same issue, I thought I was misunderstanding the documentation for a while because my definitions and responses were being generated without any `properties`.

report.go:
```golang
// Report is the payload for a submit report request; represents a report to be created
//
// swagger:model Report
type Report struct {
	// ID of the report
	// required:true
	ID string `json:"id"`

	// The report data
	Properties map[string]string `json:"properties,omitempty"`
}
```
Generates a definitions block like
```yaml
definitions:
    Report:
        description: Report is the payload for a submit report request; represents a report to be created
        x-go-package: foo/models
```
without GOROOT set, and
```yaml
definitions:
    Report:
        description: Report is the payload for a submit report request; represents a report to be created
        properties:
            id:
                description: ID of the report
                type: string
                x-go-name: ID
            properties:
                additionalProperties:
                    type: string
                description: The report data
                type: object
                x-go-name: Properties
        required:
            - id
        type: object
        x-go-package: foo/models
```
when it is set.

I'm running Ubuntu 22.10, Linux kernal `5.19.0-28-generic`
