### ISSUE TITLE
AllOf member does not generate an external $ref object

### ISSUE THREAD

**Issue by ssfilatov** [go-swagger/go-swagger#2875]
## Problem statement

https://goswagger.io/use/spec/allOf.html shows an example of how to use allOf. SimpleOne is represented as an external object which is useful for reader not to confuse it with a new object. here's how it is represented in the link above:
```
AllOfModel:
    title: "An AllOfModel is composed out of embedded structs but it should build\nan allOf property"
    allOf: 
      - $ref: "#/definitions/SimpleOne"
      ...
```

When I test almost the same code it leads me to this:
code:
```
// A SimpleOne is a model with a few simple fields
type SimpleOne struct {
	ID int64 `json:"id"`
}

type AllOfModel struct {
	// swagger:allOf
	SimpleOne
}
```
result:
```
AllOfModel:
        allOf:
            - properties:
                id:
                    format: int64
                    type: integer
              type: object
```

## Environment
swagger version: v0.30.0
go version: go1.19 darwin/amd64
OS: darwin/amd64
