### ISSUE TITLE
[Bug?] Swagger Flatten, Not Recognizing Nested Operations

### ISSUE THREAD

**Issue by nkreiger** [go-swagger/go-swagger#2908]
## Problem statement

Swagger flatten not working as expected

## Swagger specification

```yaml
  /applications:
    get:
      $ref: 'absolute_path#/paths/~1applications/get'
    post:
      $ref: 'absolute_path#/paths/~1applications/post'
```
generates:

    /applications:
        get: {}
        post: {}

but if I move it up to the root level, works fine. I cannot do this though because I want to reference specific operations. Maybe I'm doing something wrong?

this works fine with `swagger-cli`

## Steps to reproduce

swagger flatten ... --format=yaml --with-flatten=full

## Environment
swagger version: v.30.3 
go version: 1.18.0
OS:
