### ISSUE TITLE
Issue with parameters of type file in the client generator

### ISSUE THREAD

**Issue by stoyanr** [go-swagger/go-swagger#320]
The client generator has an issue with parameters of type `file`. For example, for the following swagger spec:
```yml
  /services/{serviceId}/files:
    post:
      operationId: CreateServiceFiles
      consumes:
        - multipart/form-data
      parameters:
        - name: files
          in: formData
          required: true
          type: file
```
In the `CreateServiceFilesParams` struct, the field `Files` is of type `os.File`, but is later compared to `nil`. It should either be of type `*os.File`, or the `nil` comparison should not be there.

We need this for one of our projects at SAP. It seems to be a rather small and straightforward change, I would like to contribute a PR for it.
