### ISSUE TITLE
Wrong httpkit/validate package in generated model files

### ISSUE THREAD

**Issue by easeway** [go-swagger/go-swagger#343]
Here's part of generated code:

```go
import (
	"bytes"
	"io"
	"io/ioutil"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

type Resource interface {
	httpkit.Validatable
...
```

Obviously, it should be `validate.Validatable`, not `httpkit.Validatable`

**Comment by casualjim** [comment]
can you add the relevant pieces of the swagger spec or a version that is similar?

**Comment by easeway** [comment]
here's the piece:

```yaml
definitions:
 Resource:
    description: A resource
    discriminator: resourceType
    properties:
      resourceType:
        type: string
        description: discriminating type of the resource
      name:
        type: string
        description: name of the resource
    required:
      - resourceType
      - name
```
