### ISSUE TITLE
Default value is not generated for boolean type.

### ISSUE THREAD

**Issue by vburenin** [go-swagger/go-swagger#350]
I've hit this issue with the default boolean type parameter value. For some reason, boolean default value code is not generated. For integers and strings it works just fine. 

```
parameters:
    - name: verbose
      in: query
      type: boolean
      default: false
```
