### ISSUE TITLE
Wrong enum type names in the client generator

### ISSUE THREAD

**Issue by stoyanr** [go-swagger/go-swagger#352]
The client generator has an issue with enum types when types names in the swagger file differ from the generated type names. For example, for the following type definition:

```yaml
definitions:
  slp_action_enum:
    type: string
    enum:
      - slp.action.STOP
...
```

the following code is generated in `models/slp_action_enum.go`:

```go
type SlpActionEnum string
...
func (m SlpActionEnum) validateSlpActionEnumEnum(path, location string, value slp_action_enum) error {
	if slpActionEnumEnum == nil {
		var res []slp_action_enum
...
```

In the `validateSlpActionEnumEnum` function above, the argument `value` and the variable `res` are of type `slp_action_enum`, which is incorrect since there is no such type. The correct type name is `SlpActionEnum`.
