### ISSUE TITLE
Parameters template bug leads to errors in header validation

### ISSUE THREAD

**Issue by galaxie** [go-swagger/go-swagger#494]
## Required headers params like `X-Request-ID` are never valid

It's cased by incorrect access to `request.Header` values by non-canonicalized key.

## Swagger specification
Imagine this specification
```
parameters:
  requestID:
    name: X-Request-ID
    in: header
    required: true
    type: string
```
## Steps to reproduce
Any requests with filled `X-Request-ID`  to a server generated according to the specification

Requests are never valid because of [this string](https://github.com/go-swagger/go-swagger/blob/master/generator/templates/server/parameter.gotmpl#L151)  . Keys are canonicalized in `request.Header`, so there are no `X-Request-ID` there, but `X-Request-Id`, so the incorrect map access makes `X-Request-ID in header is required` error.
