### ISSUE TITLE
Integer enum validation always fail

### ISSUE THREAD

**Issue by shirou** [go-swagger/go-swagger#523]
### Problem statement

When `enum` is specified and send a correct parameter,  `type in formData should be one of [0 1]"` returned always.

go-swagger generates validator code as follows if enum specified.

```
func (o *GetFooJSONParams) validateType(formats strfmt.Registry) error {
	if err := validate.Enum("type", "formData", *o.Type, []interface{}{0, 1}); err != nil {
		return err
	}

	return nil
}
```

Here, o.Type is `int64` because all integer converted to int64. And, `[]interface{}{0, 1}` is an `int`.
So, `reflect.DeepEqual` in a `validate.Enum()` always return `EnumFail`.

## Swagger specification

```
  /example:
    get:
      parameters:
        - name: type
          type: integer
          in: query
          enum:
            - 0
            - 1
```

## How to fix

If I change these like this manually,

```
	if err := validate.Enum("type", "formData", *o.Type, []int64{0, 1}); err != nil {
```

it works fine for me.

So, could you change to a template to use actual go type?

Thank you!
