### ISSUE TITLE
Array references are generated as array of structs rather than array of pointers.

### ISSUE THREAD

**Issue by chakrit** [go-swagger/go-swagger#59]
Example definition:

```yml
OrderPlacement:                                                                      
  properties:                                                                        
    items:                                                                           
      type: 'array'                                                                  
      items: { '$ref': '#/definitions/OrderItem' }
```

The generated server code looks like this:

```yml
// OrderPlacement                                                                      
type OrderPlacement struct {                                                           

  // Items                                                                             
  Items []OrderItem `json:"items" xml:"items"`                                         
}                                                                                      
```

Note the `[]OrderItem`. Per de facto Go conventions I think this should be `[]*OrderItem`.
