### ISSUE TITLE
Use go-swagger to generate different client/servers

### ISSUE THREAD

**Issue by Raffo** [go-swagger/go-swagger#599]
Hi, 
I am currently trying to use go-swagger to generate some part of a Server application automatically. The server has been written with the idea of code generation in mind but we would love to reuse entirely our code transforming the code in go templates. It would be actually enough the export the `appGenerator` type and have a function that returns it (maybe `generator.GenerateServer` itself?). I would then use `appGenerator` to execute the templates.
I would be interested in discussing how I could realize what I want to do, if it is possible with the current `go-swagger`  or not. 
Thanks in advance~

**Comment by casualjim** [comment]
you can provide your own templates for go-swagger the client and server generators allow you specify a directory on disk to add custom templates

There are some docs here: http://goswagger.io/generate/templates/

In VIC they do this: https://github.com/vmware/vic/tree/master/lib/apiservers/templates
https://github.com/vmware/vic/blob/master/Makefile#L274-L281

You can override these templates by using the same names
https://github.com/go-swagger/go-swagger/blob/master/generator/templates.go#L61-L73

**Comment by Raffo** [comment]
Wouldn't this generate roughly the same structure of the server? I don't want to change minor details, I want to have code that looks totally different (but only for the server part, models and clients are more than okay) while using code the parsing and validation from ```go-swagger```. This means different number of files and different functionalities. This is why I thought that having something that could return the AppGenerator could be enough, but I am interested in understanding your opinion.

**Comment by casualjim** [comment]
yeah you're right it would generate a similar structure.
Feel free to make the necessary changes for your case to work and submitting a PR.

If I understand correctly you're not happy with how the operations/parameters/responses are structured and want to replace all of it? Do you have an example of how the structure would look?

**Comment by Raffo** [comment]
Yeah, I would love to have something much simpler. I do not have the current project opensource, but I can create a gist to give you an idea as all this part can actually be opensourced. I will then work on the PR so that we can discuss further.

**Comment by Raffo** [comment]
@casualjim The server will look somehow similar to https://github.com/zalando/chimp/blob/master/api/server.go where the routes part will be generate from the swagger def. The handlers, similar to  https://github.com/zalando/chimp/blob/master/api/handler.go will be able to use something like this https://gist.github.com/Raffo/0bcc37995a15bd383944f099d94d1b82 for response generation. I hope that at least the idea is clear: I want to build a very opinionated server, with only few parts auto generated in order to satisfy an use case that pretty much matches the need of our project but to do so I want to re-use the parts of go-swagger.

**Comment by Raffo** [comment]
@casualjim Sorry for the delay, but I didn't have time at all to work on this. I quickly hacked something to give you an understanding of what I meant with this issue here: https://github.com/Raffo/go-swagger/commit/a196c5954def2bb9f1b335f7bb8011c49c5c1f08

Essentially the only thing that was done is: 
- Making appGenerator public and accessible from the outside
- Created a "main" that can be used to generate any template using Go's templates. This main should be evolved in just executing the templates based on the content of appGenerator (now it is only an hack) -> https://github.com/Raffo/go-swagger/blob/a196c5954def2bb9f1b335f7bb8011c49c5c1f08/cmd/swagger/commands/generate/cmd/main.go 

Please note that all of this is an hack and that is not definitive or well done. I just wanted to bump the discussion and give a better understanding of what I meant before.

**Comment by Raffo** [comment]
Up, any update?

**Comment by casualjim** [comment]
wouldn't it be easier to add a few a flag for a config file to customize the generation and the folder layout?

**Comment by Raffo** [comment]
Yes, but do you think it would be actually possible? It looks like the code that is generated has an enforced structure... could you give me an hint on how you would change the code?

**Comment by casualjim** [comment]
I divide the code in 4 types of generation based on the type passed to the templates as context.
Then I allow for a template to be used to specify the path with a filter for joining path parts together so that an empty path part has no effect.

The file name also gets a template so that you can customize the name of the generated file
The template name has a convention that when it starts with asset:[key] it will be looked up from the embedded templates in the swagger binary, otherwise it will look for that template on disk based on the path you specified.

That config should be in an ordered list so that the generation order is deterministic, then instead of hardcoding the generation of each known template it will now use that config and iterate over those configurations to generate the files with context.

As a bonus you'd be able to generate other languages as well from the same object model.

**Comment by casualjim** [comment]
I refactored the codegeneration to the model I described in the previous comment.
https://github.com/go-swagger/go-swagger/tree/gen-layout-configfile

it still needs the config file bit but the machinery for it has been refactored so it can be driven by a config file. The next thing that would need to be implemented is using viper or something to read a config.

**Comment by Raffo** [comment]
Nice, let me know if you would love help to get it finished and if so, what kind of help!

**Comment by casualjim** [comment]
I've added some docs on the config file format here: https://github.com/go-swagger/go-swagger/blob/gen-layout-configfile/docs/use/template_layout.md

Please let me know if this works for you, then I'll move it to master and release a 0.6.1

**Comment by Raffo** [comment]
I didn't get how to test it. I tried the following in `github.com/go-swagger/cmd/swagger`

````
 go build .
mir:swagger raffo$ swagger generate server --help
Usage:
  swagger [OPTIONS] generate server [server-OPTIONS]

generate all the files for a server application

Help Options:
  -h, --help                 Show this help message

[server command options]
      -f, --spec=            the spec file to use (default: ./swagger.json)
      -a, --api-package=     the package to save the operations (default: operations)
      -m, --model-package=   the package to save the models (default: models)
      -s, --server-package=  the package to save the server specific code (default: restapi)
      -c, --client-package=  the package to save the client specific code (default: client)
      -t, --target=          the base directory for generating the files (default: ./)
      -T, --template-dir=    alternative template override directory
      -A, --name=            the name of the application, defaults to a mangled value of info.title
      -O, --operation=       specify an operation to include, repeat for multiple
          --tags=            the tags to include, if not specified defaults to all
      -P, --principal=       the model to use for the security principal
          --default-scheme=  the default scheme for this API (default: http)
      -M, --model=           specify a model to include, repeat for multiple
          --skip-models      no models will be generated when this flag is specified
          --skip-operations  no operations will be generated when this flag is specified
          --skip-support     no supporting files will be generated when this flag is specified
          --exclude-main     exclude main function, so just generate the library
          --exclude-spec     don't embed the swagger specification
          --with-context     handlers get a context as first arg
          --dump-data        when present dumps the json for the template generator instead of generating files

mir:swagger raffo$ grep -R "config-file" .
./commands/generate/server.go: 	ConfigFile    flags.Filename `long:"config-file" short:"C" description:"configuration file to use for overriding template options"`
````

Am I doing something wrong? 

Thanks for your work!

**Comment by casualjim** [comment]
you can pass it your own set of templates and see if it meets your needs. I'm unlikely to be able to spend time on this for the next 10 days so there is no rush :).

**Comment by Raffo** [comment]
@casualjim with this example config: 

````
layout:
  application:
    - name: configure
      source: asset:serverConfigureapi
      target: "{{ joinFilePath .Target .ServerPackage }}"
      file_name: "{{ .Name }}_client.go"
      skip_exists: true
    - name: main
      source: asset:serverMain
      target: "{{ joinFilePath .Target \"cmd\" (dasherize (pascalize .Name)) }}-server"
      file_name: "main.go"
    - name: embedded_spec
      source: asset:swaggerJsonEmbed
      target: "{{ joinFilePath .Target .ServerPackage }}"
      file_name: "embedded_spec.go"
    - name: server
      source: asset:serverServer
      target: "{{ joinFilePath .Target .ServerPackage }}"
      file_name: "server.go"
    - name: builder
      source: asset:serverBuilder
      target: "{{ joinFilePath .Target .ServerPackage .Package }}"
      file_name: "{{ snakize (pascalize .Name) }}_api.go"
    - name: doc
      source: asset:serverDoc
      target: "{{ joinFilePath .Target .ServerPackage }}"
      file_name: "doc.go"
  models:
    - name: definition
      source: asset:model
      target: "{{ joinFilePath .Target .ModelPackage }}"
      file_name: "{{ (snakize (pascalize .Name)) }}.go"
  operations:
    - name: parameters
      source: asset:serverParameter
      target: "{{ joinFilePath .Target .ServerPackage .APIPackage .Package  }}"
      file_name: "{{ (snakize (pascalize .Name)) }}_parameters.go"
    - name: responses
      source: asset:serverResponses
      target: "{{ joinFilePath .Target .ServerPackage .APIPackage .Package  }}"
      file_name: "{{ (snakize (pascalize .Name)) }}_responses.go"
    - name: handler
      source: asset:serverOperation
      target: "{{ joinFilePath .Target .ServerPackage .APIPackage .Package  }}"
      file_name: "{{ (snakize (pascalize .Name)) }}.go"
````
it doesn't seeem to work and I don't get any meaningful log. Any idea of what could be wrong? Thanks again :-)
