### ISSUE TITLE
Struct references in operation parameter objects are generated as struct fields instead of pointers.

### ISSUE THREAD

**Issue by chakrit** [go-swagger/go-swagger#60]
Spec:

```yml
'/order':                                                                                
  post:                                                                                  
    tags: ['order']                                                                      
    operationId: 'postOrder'                                                             
    summary: 'Creates a new Order.'                                                      
    parameters:                                                                          
      - name: 'order'                                                                    
        in: 'body'                                                                       
        required: true                                                                   
        schema: { '$ref': '#/definitions/OrderPlacement' }                               
```

Generated handler looks like this:

```go
// PostOrderHandlerFunc turns a function with the right signature into a post order handler
type PostOrderHandlerFunc func(PostOrderParams, *models.Principal) (*models.Result, error) 
                                                                                           
func (fn PostOrderHandlerFunc) Handle(params PostOrderParams, principal *models.Principal) (*models.Result, error) {
  return fn(params, principal)                                                             
}
```

And the generated parameter object looks like this:

```go
// PostOrderParams contains all the bound params for the post order operation       
// typically these are obtained from a http.Request                                 
type PostOrderParams struct {                                                       
  // info about the order to place, along with payment authorization token.         
  Order models.OrderPlacement                                                       
}
```

I think either:

* The `Order` field should be a pointer or...
* The `PostOrderParams` in the handler signature should be a pointer.

**Comment by casualjim** [comment]
ah here it's actually expected.
To get a pointer here the spec should read:

```yaml
'/order':                                                                                
  post:                                                                                  
    tags: ['order']                                                                      
    operationId: 'postOrder'                                                             
    summary: 'Creates a new Order.'                                                      
    parameters:                                                                          
      - name: 'order'                                                                    
        in: 'body'                                                                       
        required: true                                                                   
        schema: { '$ref': '#/definitions/OrderPlacement' }  
```
