### ISSUE TITLE
uuid cannot be converted to string

### ISSUE THREAD

**Issue by amandafeng001** [go-swagger/go-swagger#628]
## Problem statement

if a parameter is set to "type:string, format:uuid, required:false", 
"go run" gives  this error: "_...cannot convert o.ID (type *strfmt.UUID) to type string"_.

However, if set the parameter to " type:string, format:uuid, required:true", this issue is not observed.

**Comment by casualjim** [comment]
another failure related to this one:

```
/workspace/metadata:
    get:
      parameters:
        - name: "workspace_id"
          in: "query"
          required: true
          minItems: 1
          type: "array"
          items:
            type: "string"
            format: "uuid"
```
