### ISSUE TITLE
Question: How to parse mongo ISODate format

### ISSUE THREAD

**Issue by xuanzhaopeng** [go-swagger/go-swagger#670]
## Problem statement

Hi,
Maybe this question should point to openapi or mgo, but I still want to share this question, maybe could get some ideas.

As I use mgo for Mongo driver , thus I defined the swagger model as :

``` yml
...
definitions:
  myitem:
    type: object
    properties:
      inserttime:
        type: string
        format: date-time
```

Thus in go swagger, I get :

``` go
    Inserttime strfmt.DateTime `json:"inserttime,omitempty"`
```

When I get mongo result by model generated by swagger , then the time is :

> 0001-01-01T00:00:00.000Z

But when I change the model to 

``` go
    Inserttime time.Time `json:"inserttime,omitempty"`
```

Then I get time is :

> 2016-09-25T20:03:21.567Z

Then I see the definition of "strfmt.DateTime",  defined as :

``` go
    type DateTime time.Time
```

So I'm very confused ....why it doesn't work with strfmt.DateTime?

Any idea? Thanks a lot
