### ISSUE TITLE
x-go-name not respected in "swagger generate model"

### ISSUE THREAD

**Issue by ethanfrey** [go-swagger/go-swagger#701]
## Problem statement

I want a different name in json as in go (the web developer keeps requesting name changes, and I don't want to change my go code each time).  I tried to use `x-go-name`, which seems the way to do this.

In a related note, when I want to get rid of omittempty, I seem to need to add `x-nullable: false` and make it required.  Here I really want to return 0 rather than omit it.  Is there some easier way to do this?

## Swagger specification

```
  ViewWindow:
    title: The view window as two rotational angles, and the field of view (opening)
    type: object
    properties:
      yaw:
        type: number
        description: horizontal rotation in radians
        example: -0.982
        x-nullable: false
      pitch:
        type: number
        description: vertical rotation in radians
        example: 1.32
        x-nullable: false
      field_of_view:
        type: number
        description: field of view in radians (1 / zoom)
        example: 0.54
        x-nullable: false
        x-go-name: Fov
    required: ['yaw', 'pitch', 'field_of_view']
```

Go Code:

```
// ViewWindow The view window as two rotational angles, and the field of view (opening)
// swagger:model ViewWindow
type ViewWindow struct {

	// field of view in radians (1 / zoom)
	// Required: true
	FieldOfView float64 `json:"field_of_view"`

	// vertical rotation in radians
	// Required: true
	Pitch float64 `json:"pitch"`

	// horizontal rotation in radians
	// Required: true
	Yaw float64 `json:"yaw"`
}
```

## Steps to reproduce

Ran this with the most recent master (commit `6755c2f`)
