### ISSUE TITLE
Is it possible to do the reverse routing?

### ISSUE THREAD

**Issue by anisimovsergey** [go-swagger/go-swagger#714]
In order to respond with the code 201 Created, I want to add Location header according to [RFC 2116](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.30) pointing to the created resource.

Is it possible to do the reverse routing in such case? Something similar to [Gorilla reverse](http://www.gorillatoolkit.org/pkg/reverse#files)?

**Comment by casualjim** [comment]
We currently don't have reverse routing, I think it would be a great addition to the runtime package.

You can define the response though:

```yaml
        '201':
          description: Created Pet
          Location:
            description: uri of the new pet
            type: string
            format: uri
```

**Comment by anisimovsergey** [comment]
Thank you for the suggestion but I feel like it should be like this:
```yaml
201:
  description: Pet created
  headers:
    Location:
      description: uri of the new pet
      type: string
      format: uri          
```
I think I've seen in the docs somewhere a notice that it's possible to replace the default router. Maybe I can use Gorila's mux or something instead of denco and get the reverse routing even though it's gonna be slower. Do you have any example of how to do that?
