### ISSUE TITLE
additional properties: false still gets treated as if it was set to true

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#73]
provided as part a comment on issue #72, it incorrectly detects this as an object with additional properties.

```yaml
  RunParameters:
    additionalProperties: false
    type: object
    description: Optional run parameters for activating the build trigger
    properties:
      branch_name:
        type: string
        description: '(SCM only) If specified, the name of the branch to build.'
      refs:
        type: object
        description: '(SCM Only) If specified, the ref to build.'
      commit_sha:
        type: string
        description: '(Custom Only) If specified, the ref/SHA1 used to checkout a git repository.'
```
