### ISSUE TITLE
What is the proper way to vendor go-swagger?

### ISSUE THREAD

**Issue by Ravenwater** [go-swagger/go-swagger#730]
I am trying to vendor an API generated by go-swagger to be included in a Docker container. 

> govendor list 
> .....

shows many packages, what is the minimum set?

**Comment by casualjim** [comment]
For this generation to compile you need to have some packages in your GOPATH:

  * github.com/go-openapi/runtime
  * github.com/tylerb/graceful
  * github.com/jessevdk/go-flags
  * golang.org/x/net/context

So that boils down to you have to vendor those packages and you should be good. the go-swagger repo contains all the CLI stuff for the generators, but that's more like build tool not something you'd depend on in code.

**Comment by Ravenwater** [comment]
What about github.com/gorilla/mux, being called from the routers.go? This is where it goes all wrong for me:
root@14d0c9d922ba:/go/src/medicarepathfinder/scoring_engine_mvp# go build api/v0.1.0/swagger-editor-gen/go-server/main.go
api/v0.1.0/swagger-editor-gen/go-server/go/routers.go:6:2: cannot find package "github.com/gorilla/mux" in any of:
        /go/src/medicarepathfinder/scoring_engine_mvp/vendor/github.com/gorilla/mux (vendor tree)
        /usr/local/go/src/github.com/gorilla/mux (from $GOROOT)
        /go/src/github.com/gorilla/mux (from $GOPATH)

I then vendored github.com/gorilla/mux and rebuild the container:
C:\Users\Theodore\dev\Golang\src\github.com\medicarepathfinder\scoring_engine_mvp>govendor list +v
 v  github.com/go-openapi/runtime
 v  github.com/gorilla/mux
 v  github.com/jessevdk/go-flags
 v  github.com/tylerb/graceful
 v  golang.org/x/net/context

root@c64e272829ae:/go/src/medicarepathfinder/scoring_engine_mvp# go build api/v0.1.0/swagger-editor-gen/go-server/main.go
api/v0.1.0/swagger-editor-gen/go-server/go/routers.go:6:2: cannot find package "_/go/src/medicarepathfinder/scoring_engine_mvp/vendor/github.com/gorilla/mux" in any of:
        /usr/local/go/src/_/go/src/medicarepathfinder/scoring_engine_mvp/vendor/github.com/gorilla/mux (from $GOROOT)
        /go/src/_/go/src/medicarepathfinder/scoring_engine_mvp/vendor/github.com/gorilla/mux (from $GOPATH)

For some reason that github.com/gorilla/mux package is not getting referenced properly: the package that is searched for is

-> "_/go/src/medicarepathfinder/scoring_engine_mvp/vendor/github.com/gorilla/mux"
instead of
-> "github.com/gorilla/mux"

I don't know where that "_/go/src/bla" is coming from.

**Comment by Ravenwater** [comment]
I am trying to isolate this problem, so I built a little gorilla/mux server to see if I could reproduce the problems above.  And I can't yet, so at this point, it is still hypothesized to be a problem in the swagger way of doing organizing the code.

C:\Users\Theodore\dev\Golang\src\github.com\Ravenwater\gorilla_mux_test>tree vendor
Folder PATH listing for volume Windows8_OS
Volume serial number is 4EEE-9530
C:\USERS\THEODORE\DEV\GOLANG\SRC\GITHUB.COM\RAVENWATER\GORILLA_MUX_TEST\VENDOR
└───github.com
    └───gorilla
        ├───context
        └───mux

C:\Users\Theodore\dev\Golang\src\github.com\Ravenwater\gorilla_mux_test>govendor list
 v  github.com/gorilla/context
 v  github.com/gorilla/mux
pl  github.com/Ravenwater/gorilla_mux_test
C:\Users\Theodore\dev\Golang\src\github.com\Ravenwater\gorilla_mux_test>go build main.go
C:\Users\Theodore\dev\Golang\src\github.com\Ravenwater\gorilla_mux_test>ls
main.exe  main.go  vendor

**Comment by willis7** [comment]
I use [glide](https://github.com/Masterminds/glide) and a simple `glide init` followed by `glide install` after generating the code worked perfectly. The dependencies were correctly identified and downloaded no problem.

**Comment by l3x** [comment]
I used glide but got the following error:

```
[ERROR]	Error scanning github.com/go-swagger/go-swagger/examples/authentication/client/customers: open /Users/lex/.glide/cache/src/https-github.com-go-swagger-go-swagger/examples/authentication/client/customers: no such file or directory
[ERROR]	This error means the referenced package was not found.
[ERROR]	Missing file or directory errors usually occur when multiple packages
[ERROR]	share a common dependency and the first reference encountered by the scanner
[ERROR]	sets the version to one that does not contain a subpackage needed required
[ERROR]	by another package that uses the shared dependency. Try setting a
[ERROR]	version in your glide.yaml that works for all packages that share this
[ERROR]	dependency.
```

What would be the exact configuration line to use in the glide.yaml file (or other ideas) to fix this?

Thanks, in advance.

**Comment by casualjim** [comment]
I use this yaml in my projects for the go-swagger stuff.

You're not meant to vendor go-swagger directly, there is a much smaller runtime package. In glide I have to list out its dependencies.

```yaml
package: github.com/casualjim/private
import:
- package: github.com/go-openapi/errors
- package: github.com/go-openapi/loads
- package: github.com/go-openapi/runtime
  subpackages:
  - client
  - flagext
  - middleware
- package: github.com/go-openapi/spec
- package: github.com/go-openapi/strfmt
- package: github.com/go-openapi/swag
- package: github.com/go-openapi/validate
- package: github.com/tylerb/graceful
  version: ^1.2.15
- package: golang.org/x/net
  subpackages:
  - context
- package: github.com/mailru/easyjson
  version: master
  subpackages:
  - buffer
  - jlexer
  - jwriter
```
