### ISSUE TITLE
enum validation for anonymous nested object is missing

### ISSUE THREAD

**Issue by casualjim** [go-swagger/go-swagger#74]
Provided as part of issue #72 the enum of the anonymous schema under delegate comes out without a validation.

```yaml
  NewPrototype:
    required:
      - role
      - delegate
    type: object
    description: Description of a new prototype
    properties:
      activating_user:
        required:
          - name
        type: object
        description: Repository creating user to whom the rule should apply
        properties:
          name:
            type: string
            description: The username for the activating_user
      role:
        enum:
          - read
          - write
          - admin
        type: string
        description: Role that should be applied to the delegate
      delegate:
        required:
          - name
          - kind
        type: object
        description: Information about the user or team to which the rule grants access
        properties:
          kind:
            enum:
              - user
              - team
            type: string
            description: Whether the delegate is a user or a team
          name:
            type: string
            description: The name for the delegate team or user
```
