### ISSUE TITLE
Unmarshal error returned without further context

### ISSUE THREAD

**Issue by wlcx** [go-swagger/go-swagger#77]
Running `swagger generate client` on a spec which has passed `swagger validate` (At least, the command exited with no errors/output....) is resulting in the following: 
```
$ swagger generate client -f swagger.json
json: cannot unmarshal bool into Go value of type string
```

Is there an easy way to see where this has been generated to work out what the problem is?

**Comment by casualjim** [comment]
would it be possible to show me the spec?

**Comment by casualjim** [comment]
this might be because of lack of a space between the colon after a key and the value

results in the error:
```yaml
definitions:
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type:string
```


correct: 
```yaml
definitions:
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
```
