### ISSUE TITLE
How to separate empty or 0 for Integer property in Model

### ISSUE THREAD

**Issue by yangjunsss** [go-swagger/go-swagger#770]
## Problem statement
Define a model like this,request content type is application/json :

```yaml
 user:
    type: object
    properties:
      role:
        type: integer
        enum:
          - 0
          - 1
          - 10
          - 11
          - 20
```

it's used for a POST method for updating something and the 'role' is not required and '0' is valid value. But if the role is not set, the value is 0 either. How can I separate the two scenario 0 value and empty?

Test Code like this:
```go

var body models.User
b := []byte(`{}`)
json.Unmarshal(b, &body)
t.Logf("%+v %v", body, swag.IsZero(body.Status))
```
__print: {Role:0 } true__
So how about use *int instead of int? just my advise

## Swagger specification
$ swagger version
dev

**Comment by casualjim** [comment]
```yaml
 user:
    type: object
    required:
      - role
    properties:
      role:
        type: integer
        enum:
          - 0
          - 1
          - 10
          - 11
          - 20
```

or

```yaml
 user:
    type: object
    properties:
      role:
        type: integer
        x-nullable: true
        enum:
          - 0
          - 1
          - 10
          - 11
          - 20
```
