### ISSUE TITLE
Invalid enum validation check

### ISSUE THREAD

**Issue by SandyWalsh** [go-swagger/go-swagger#804]
## Problem statement

Likely related to #786 ...

Given a spec with a property of
```
       product_type:
         description: The type of product this mosaic is
         enum:⋅
           - basemap
             timelapse
             l3m
```

I'm getting this code on the client and server gen code:

```
func init() {
    var res []string
    if err := json.Unmarshal([]byte(`["basemap timelapse l3m"]`), &res); err != nil {
        panic(err)
    }
...
}
```

I suspect it should be 

```
json.Unmarshal([]byte(`["basemap", "timelapse", "l3m"]`), &res);
```

**Comment by casualjim** [comment]
it's true to the spec, change it to

```yaml
product_type:
         description: The type of product this mosaic is
         enum:⋅
           - basemap
           - timelapse
           - l3m
```
