### ISSUE TITLE
Parameter names with brackets fail to generate valid Go variables

### ISSUE THREAD

**Issue by dacamp** [go-swagger/go-swagger#809]
## Problem statement
I believe there is a regression in release `0.7.4`, specifically 51aca22.  When parameter names include brackets (`var[]`) the generator fails to sanitize the variable names.

## Steps to reproduce

NOTE: the expected URL params would be `/foo?groups[]=bar&groups[]=baz`

YAML spec
```yaml
/foo:
  get:
    parameters:
      - name: "groups[]"
        in: query
        type: array
        collectionFormat: multi
        items:
          type: string
```

Which is then rendered as this:

```go
func (o *FindFooParams) bindGroups(rawData []string, hasKey bool, formats strfmt.Registry) error {

  groups[]IC := rawData

  if len(groups[]IC) == 0 {
    return nil
  }

var groups[]IR []string
for _, groups[]IV := range groups[]IC {
  groups[]I := groups[]IV
```
