### ISSUE TITLE
Support default value for model property

### ISSUE THREAD

**Issue by Simon-Li** [go-swagger/go-swagger#828]
## Problem statement
Default value not working for model property.

## Swagger specification
```
definitions:
  item:
    type: object
    default:
      description: Test string for default values
    properties:
      description:
        type: string

```
## Steps to reproduce
Server side does not make up the default value of the property if posted without it.

Issue same as previous #769
