### ISSUE TITLE
"swagger generate model" doesn't generate enum values if "--skip-validator" is passed

### ISSUE THREAD

**Issue by kojustin** [go-swagger/go-swagger#860]
## Problem statement
"swagger generate model" doesn't generate enum values if "--skip-validator" is passed. Even when validation functions aren't wanted, I still want the enum constant values to be generated.

go-swagger 0.8.0

## Swagger specification
```
definitions:
  Status:
    type: object
    description: |
      some object
    properties:
      status:
        description: status
        type: string
        enum:
          - Good
          - Bad
          - Ok
          - Decent
          - Middling
          - Horrible
```

## Steps to reproduce
```
$ /usr/local/Cellar/go-swagger/0.8.0/bin/swagger generate model --skip-validation --spec=swag.yml
$ cat models/status.go 
package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Status some object
//
// swagger:model Status
type Status struct {

	// status
	Status string `json:"status,omitempty"`
}
```
