### ISSUE TITLE
Non-compiling generated code when parameter is array type with enum validation and underscore in name

### ISSUE THREAD

**Issue by vsayer** [go-swagger/go-swagger#863]
## Problem statement
If there is a query parameter that meets the following criteria:
1. The name has an underscore, e.g., some_parameter
2. The type is an array (of strings for the case I found)
3. The items of that array undergo enum validation

## Swagger specification
```
get:
   ...
   ...
   parameters:
     - name: some_parameter
        in: query
        ...
        type: array
        items:
          type: string
          enum:
            - enum1
            - enum2
            - enum3
```

The result of running swagger produces generated code that does not compile at the following sha: e4738db

In the generated code for getting the parameters, there's code like this:
```
someParameterI := someParameterIV

if err := validate.Enum(fmt.Sprintf("%s.%v", "some_parameter", i), "query", some_parameterI, []interface{}{"enum1", "enum2", "enum3"}); err != nil {
	return err
}
```

which obviously does not compile.
