### ISSUE TITLE
Question: Defining bson ID response from mongoDB

### ISSUE THREAD

**Issue by CuBiC3D** [go-swagger/go-swagger#884]
Struggling with go-swagger and mongoDB:
*_id* returned from mongoDB using mgo driver is of type *bson.ObjectId*.

Example model:
```yaml
Message:
  type: object
  required:
    - text
  properties:
    id:
      type: string
      readOnly: true
    text:
      type: string
```

When I get *Messages* from DB by
```go
...
messages := []*models.Message{}
if err := c.Find(nil).All(&messages); err != nil {
  log.Print("Error on getting messages: ", err)
}
return message.NewGetMessageOK().WithPayload(messages)
```
The API response omitting the *id* property. Actually it's even stored as an empty string in mongoDB.
```
HTTP/1.1 200 OK
Content-Length: 774
Content-Type: application/json
Date: Sat, 21 Jan 2017 20:53:08 GMT

[
  {
    "text": "string"
  }
]
```
Is there any way to cast the *bson.ObjectId* to something that the generated server can work with or do I have to use the opposite approach by writing the server and generate the swagger spec afterwards?
And by the way, what effect do readOnly have since it's possible to POST that parameter against the API?

**Comment by rjeczalik** [comment]
If you named your field `_id` instead of `id` I think you'd be able to read it. Like:

```yaml
Message:
  type: object
  required:
    - _id
    - text
  properties:
    _id:
      type: string
    text:
      type: string
```
