### ISSUE TITLE
Is there a workaround to determine if a field has been set but is null before #557 is completed?

### ISSUE THREAD

**Issue by christianklotz** [go-swagger/go-swagger#923]
## Problem statement

For a `PATCH` handler I'm trying to determine whether a field has been set or not. I saw there's work going on in #557 which looks to solve exactly the same problem 🙇 but obviously isn't exactly a trivial change.

Is there a way to work around this temporarily, getting/creating a map of the fields that have been set or something like that?

## Swagger specification
The snipped below is just how I defined the request body.

```yaml
  MyUpdateParams:
    description: Entity to perform changes on an existing resource.
    type: object
    properties:
      profile_id:
        description: |
          Profile id the resource should be assigned to or null for anonymous resources. 
          If provided but set to null it will be changed whereas if the field is unset, no 
          change will be performed.
        type: string
        format: uuid
        x-nullable: true
```
