### ISSUE TITLE
Validation for extended string format

### ISSUE THREAD

**Issue by RomanBuzuk** [go-swagger/go-swagger#961]
## Problem statement

We can define that some property has extended string format ( for example ipv4). Then go-swagger generate this property with special type ( for ipv4 it is *strfmt.IPv4). But generated code don`t do validation for this type.
## Example:
swagger.yaml 
```
definitions:
  ethernet:
    type: object
    required:
      - ip
    properties:
      id:
        type: integer
        format: int32
        readOnly: true
      ip:
        type: string
        format: ipv4
```
We get file ethernet.go with code 
```
...
type Ethernet struct {
	// id
	// Read Only: true
	ID int32 `json:"id,omitempty"`

	// ip
	// Required: true
	IP *strfmt.IPv4 `json:"ip"`
}
...
func (m *Ethernet) validateIP(formats strfmt.Registry) error {

	if err := validate.Required("ip", "body", m.IP); err != nil {
		return err
	}
	return nil
}
```
But why  it is not generated like this : 
```
func (m *Ethernet) validateIP(formats strfmt.Registry) error {

	if err := validate.Required("ip", "body", m.IP); err != nil {
		return err
	}
// check that we get string in right format
	if err := validate.FormatOf("ip", "body", "ipv4", m.IP.String(), formats); err != nil {
		return err
	}
	return nil
}
```

## Environment
swagger version: 0.8.0
