### ISSUE TITLE
String parameter in body and query

### ISSUE THREAD

**Issue by RomanBuzuk** [go-swagger/go-swagger#990]
## Problem statement

I want to create operation with string parameter in body. Goswagger fails while generating with runtime error. But, if i change  body to query, it works.
How can I send my parameter in body with type string?
## Swagger specification
It falls with panic: runtime error: invalid memory address or nil pointer dereference
```
    post:
      description: post func
      operationId: postfunc
      parameters:
      - name: myparam
        in: body
        type: string
```
And it works 
```
    post:
      description: post func
      operationId: postfunc
      parameters:
      - name: myparam
        in: query
        type: string
```
## Steps to reproduce
swagger generate server -A server-swagger -f ./swagger.yml
## Environment
swagger version: 0.8.0 
OS:   Ubuntu 14.04

**Comment by gregmarr** [comment]
```
    post:
      description: post func
      operationId: postfunc
      schema:
        parameters:
        - name: myparam
          in: body
          type: string
```

**Comment by RomanBuzuk** [comment]
Thanks, I fixed problem with schema
```
post:
      description: post func
      operationId: postfunc
      parameters:
      - name: myparam
        in: body
        required: true
        schema:
          type: string
```

But, I think Goswagger should not fail with panic, while generating. It must be some error message about wrong parameters, not runtime error.
